// SPDX-FileCopyrightText: 2026 Uwe Jugel
// SPDX-License-Identifier: AGPL-3.0-or-later

// Generates spec/colors.json — the full xterm-256 palette documented with a
// long name, a 3-letter short name, a hex value, and a human description for
// every index 0-255. The 16 system colors and a curated set of popular colors
// (orange, teal, navy, …) get real names + shorts; the rest get systematic
// rgbRGB / grayNN names. Both the long name and the short are accepted wherever
// the picker resolves a color (e.g. spec/strings.json multi_select_bg).
// Run: go run ./scripts/gen_colors/
package main

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
)

// colorEntry is one documented palette slot.
type colorEntry struct {
	I     int      `json:"i"`
	Name  string   `json:"name"`
	Short string   `json:"short,omitempty"`
	Hex   string   `json:"hex"`
	Desc  string   `json:"desc"`
	Alt   []string `json:"alt,omitempty"`
}

// named overrides the systematic name/short for a given index. Alt entries keep
// the systematic rgbRGB/grayNN name reachable as an alias.
type named struct {
	name  string
	short string
}

// system holds the 16 ANSI base colors (long name + 3-letter short).
var system = [16]named{
	{"black", "blk"}, {"maroon", "mar"}, {"green", "grn"}, {"olive", "oli"},
	{"navy", "nvy"}, {"purple", "pur"}, {"teal", "tea"}, {"silver", "sil"},
	{"gray", "gry"}, {"red", "red"}, {"lime", "lim"}, {"yellow", "ylw"},
	{"blue", "blu"}, {"magenta", "mag"}, {"cyan", "cyn"}, {"white", "wht"},
}

// popular maps well-known xterm indices to friendly names so people can type a
// colour by feel ("orange", "pink") instead of memorising the cube formula.
var popular = map[int]named{
	196: {"brightred", "brd"}, 46: {"brightgreen", "bgn"}, 21: {"brightblue", "bbl"},
	51: {"brightcyan", "bcy"}, 201: {"brightmagenta", "bmg"}, 226: {"brightyellow", "byl"},
	208: {"orange", "org"}, 202: {"darkorange", "dor"}, 214: {"amber", "amb"},
	220: {"gold", "gld"}, 200: {"pink", "pnk"}, 198: {"hotpink", "hpk"},
	205: {"rose", "ros"}, 93: {"violet", "vio"}, 99: {"indigo", "ind"},
	54: {"darkviolet", "dvi"}, 30: {"darkteal", "dtl"}, 22: {"forest", "fst"},
	28: {"darkgreen", "dgn"}, 17: {"darknavy", "dnv"}, 33: {"azure", "azr"},
	39: {"skyblue", "sky"}, 111: {"lightblue", "lbl"}, 153: {"paleblue", "pbl"},
	94: {"brown", "brn"}, 130: {"sienna", "sie"}, 137: {"tan", "tan"},
	180: {"wheat", "wht2"}, 143: {"khaki", "khk"}, 100: {"darkolive", "dol"},
	160: {"crimson", "crm"}, 124: {"darkred", "drd"}, 88: {"darkmaroon", "dmr"},
	29: {"seagreen", "sea"}, 35: {"mint", "mnt"}, 121: {"palegreen", "pgn"},
	159: {"paleturquoise", "ptq"}, 183: {"plum", "plm"}, 60: {"slate", "slt"},
	67: {"steelblue", "stl"}, 245: {"midgray", "mgy"}, 240: {"darkgray", "dgy"},
	250: {"lightgray", "lgy"}, 244: {"dimgray", "dmg"},
}

// cubeLevels are the six channel intensities of the 6×6×6 colour cube.
var cubeLevels = [6]int{0, 95, 135, 175, 215, 255}

func main() {
	colors := make([]colorEntry, 0, 256)

	// 0-15: system colours.
	for i := range 16 {
		r, g, b := systemRGB(i)
		colors = append(colors, colorEntry{
			I: i, Name: system[i].name, Short: system[i].short,
			Hex: hex(r, g, b), Desc: describe(r, g, b),
		})
	}

	// 16-231: the 6×6×6 cube.
	for i := 16; i <= 231; i++ {
		n := i - 16
		r := cubeLevels[n/36]
		g := cubeLevels[(n/6)%6]
		b := cubeLevels[n%6]
		canon := fmt.Sprintf("rgb%d%d%d", n/36, (n/6)%6, n%6)
		colors = append(colors, withName(i, canon, r, g, b))
	}

	// 232-255: the 24-step grayscale ramp.
	for i := 232; i <= 255; i++ {
		v := 8 + (i-232)*10
		canon := fmt.Sprintf("gray%d", i-232)
		colors = append(colors, withName(i, canon, v, v, v))
	}

	out := map[string]any{
		"description": "Full xterm-256 palette. Each entry: i (index 0-255), " +
			"name (long), short (3-letter), hex, desc (human colour family). " +
			"Both name and short resolve anywhere the picker takes a colour " +
			"(e.g. multi_select_bg in spec/strings.json) — else use the numeric " +
			"index. System colours (0-15) and popular colours get friendly names; " +
			"the rest use systematic rgbRGB / grayN names (cube level digits 0-5). " +
			"Generated by scripts/gen_colors — run `make gen-colors` to regenerate.",
		"colors": colors,
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(out); err != nil {
		fmt.Fprintln(os.Stderr, "encode:", err)
		os.Exit(1)
	}
}

// withName builds a cube/gray entry, applying a popular-name override (keeping
// the systematic name reachable as an alias) when one exists.
func withName(i int, canon string, r, g, b int) colorEntry {
	e := colorEntry{I: i, Name: canon, Hex: hex(r, g, b), Desc: describe(r, g, b)}
	if p, ok := popular[i]; ok {
		e.Name = p.name
		e.Short = p.short
		e.Alt = []string{canon}
	}
	return e
}

func hex(r, g, b int) string { return fmt.Sprintf("#%02x%02x%02x", r, g, b) }

// systemRGB returns the conventional RGB for an ANSI system colour (0-15).
func systemRGB(i int) (int, int, int) {
	base := [16][3]int{
		{0, 0, 0}, {128, 0, 0}, {0, 128, 0}, {128, 128, 0},
		{0, 0, 128}, {128, 0, 128}, {0, 128, 128}, {192, 192, 192},
		{128, 128, 128}, {255, 0, 0}, {0, 255, 0}, {255, 255, 0},
		{0, 0, 255}, {255, 0, 255}, {0, 255, 255}, {255, 255, 255},
	}
	return base[i][0], base[i][1], base[i][2]
}

// describe returns a short human colour family like "dark green" or "pale cyan"
// for documentation. Grays are detected by equal channels.
func describe(r, g, b int) string {
	maxc := math.Max(float64(r), math.Max(float64(g), float64(b)))
	minc := math.Min(float64(r), math.Min(float64(g), float64(b)))
	v := maxc / 255.0
	if maxc == minc {
		switch {
		case maxc == 0:
			return "black"
		case v < 0.30:
			return "dark gray"
		case v < 0.65:
			return "gray"
		case v < 0.95:
			return "light gray"
		default:
			return "white"
		}
	}
	sat := (maxc - minc) / maxc
	hue := hueOf(float64(r), float64(g), float64(b), maxc, minc)
	names := []string{
		"red", "orange", "yellow", "chartreuse", "green", "spring green",
		"cyan", "azure", "blue", "violet", "magenta", "rose",
	}
	family := names[int(math.Mod(hue/30.0+0.5, 12))]

	var light string
	switch {
	case v < 0.45:
		light = "dark "
	case sat < 0.35:
		light = "pale "
	case v > 0.85 && sat < 0.7:
		light = "light "
	}
	return light + family
}

// hueOf returns the colour hue in degrees [0,360).
func hueOf(r, g, b, maxc, minc float64) float64 {
	d := maxc - minc
	var h float64
	switch maxc {
	case r:
		h = math.Mod((g-b)/d, 6)
	case g:
		h = (b-r)/d + 2
	default:
		h = (r-g)/d + 4
	}
	h *= 60
	if h < 0 {
		h += 360
	}
	return h
}
