/*
 * SPDX-FileCopyrightText: 2026 Uwe Jugel
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

const EMOJI_DB = [
  ["😀", "grinning face", "grinning face smile happy"],
  ["😃", "grinning face with big eyes", "grinning face with big eyes happy joy haha smiley"],
  ["😄", "grinning face with smiling eyes", "grinning face with smiling eyes happy joy laugh pleased smile"],
  ["😁", "beaming face with smiling eyes", "beaming face with smiling eyes grin"],
  ["😆", "grinning squinting face", "grinning squinting face happy haha laughing satisfied"],
  ["😅", "grinning face with sweat", "grinning face with sweat hot smile"],
  ["🤣", "rolling on the floor laughing", "rolling on the floor laughing lol rofl"],
  ["😂", "face with tears of joy", "face with tears of joy"],
  ["🙂", "slightly smiling face", "slightly smiling face"],
  ["🙃", "upside-down face", "upside down face"],
  ["🫠", "melting face", "melting face sarcasm dread"],
  ["😉", "winking face", "winking face flirt wink"],
  ["😊", "smiling face with smiling eyes", "smiling face with eyes proud blush"],
  ["😇", "smiling face with halo", "smiling face with halo angel innocent"],
  ["🥰", "smiling face with hearts", "smiling face with hearts love three"],
  ["😍", "smiling face with heart-eyes", "smiling face with heart eyes love crush"],
  ["🤩", "star-struck", "star struck eyes"],
  ["😘", "face blowing a kiss", "face blowing a kiss flirt kissing heart"],
  ["😗", "kissing face", "kissing face"],
  ["☺️", "smiling face", "smiling face blush pleased relaxed"],
  ["😚", "kissing face with closed eyes", "kissing face with closed eyes"],
  ["😙", "kissing face with smiling eyes", "kissing face with smiling eyes"],
  ["🥲", "smiling face with tear", "smiling face with tear"],
  ["😋", "face savoring food", "face savoring food tongue lick yum"],
  ["😛", "face with tongue", "face with tongue stuck out"],
  ["😜", "winking face with tongue", "winking face with tongue prank silly stuck out eye"],
  ["🤪", "zany face", "zany face goofy wacky"],
  ["😝", "squinting face with tongue", "squinting face with tongue prank stuck out closed eyes"],
  ["🤑", "money-mouth face", "money mouth face rich"],
  ["🤗", "smiling face with open hands", "smiling face with open hands hugs"],
  ["🤭", "face with hand over mouth", "face with hand over mouth quiet whoops"],
  ["🫢", "face with open eyes and hand over mouth", "face with open eyes and hand over mouth gasp shock"],
  ["🫣", "face with peeking eye", "face with peeking eye"],
  ["🤫", "shushing face", "shushing face silence quiet"],
  ["🤔", "thinking face", "thinking face"],
  ["🫡", "saluting face", "saluting face respect"],
  ["🤐", "zipper-mouth face", "zipper mouth face silence hush"],
  ["🤨", "face with raised eyebrow", "face with raised eyebrow suspicious"],
  ["😐", "neutral face", "neutral face meh"],
  ["😑", "expressionless face", "expressionless face"],
  ["😶", "face without mouth", "face without mouth mute silence no"],
  ["🫥", "dotted line face", "dotted line face invisible"],
  ["😶\u200d🌫️", "face in clouds", "face in clouds"],
  ["😏", "smirking face", "smirking face smug smirk"],
  ["😒", "unamused face", "unamused face meh"],
  ["🙄", "face with rolling eyes", "face with rolling eyes roll"],
  ["😬", "grimacing face", "grimacing face"],
  ["😮\u200d💨", "face exhaling", "face exhaling"],
  ["🤥", "lying face", "lying face liar"],
  ["🫨", "shaking face", "shaking face shock"],
  ["😌", "relieved face", "relieved face whew"],
  ["😔", "pensive face", "pensive face"],
  ["😪", "sleepy face", "sleepy face tired"],
  ["🤤", "drooling face", "drooling face"],
  ["😴", "sleeping face", "sleeping face zzz"],
  ["😷", "face with medical mask", "face with medical mask sick ill"],
  ["🤒", "face with thermometer", "face with thermometer sick"],
  ["🤕", "face with head-bandage", "face with head bandage hurt"],
  ["🤢", "nauseated face", "nauseated face sick barf disgusted"],
  ["🤮", "face vomiting", "face vomiting barf sick"],
  ["🤧", "sneezing face", "sneezing face achoo sick"],
  ["🥵", "hot face", "hot face heat sweating"],
  ["🥶", "cold face", "cold face freezing ice"],
  ["🥴", "woozy face", "woozy face groggy"],
  ["😵", "face with crossed-out eyes", "face with crossed out eyes dizzy"],
  ["😵\u200d💫", "face with spiral eyes", "face with spiral eyes"],
  ["🤯", "exploding head", "exploding head mind blown"],
  ["🤠", "cowboy hat face", "cowboy hat face"],
  ["🥳", "partying face", "partying face celebration birthday"],
  ["🥸", "disguised face", "disguised face"],
  ["😎", "smiling face with sunglasses", "smiling face with sunglasses cool"],
  ["🤓", "nerd face", "nerd face geek glasses"],
  ["🧐", "face with monocle", "face with monocle"],
  ["😕", "confused face", "confused face"],
  ["🫤", "face with diagonal mouth", "face with diagonal mouth confused"],
  ["😟", "worried face", "worried face nervous"],
  ["🙁", "slightly frowning face", "slightly frowning face"],
  ["☹️", "frowning face", "frowning face"],
  ["😮", "face with open mouth", "face with open mouth surprise impressed wow"],
  ["😯", "hushed face", "hushed face silence speechless"],
  ["😲", "astonished face", "astonished face amazed gasp"],
  ["😳", "flushed face", "flushed face"],
  ["🥺", "pleading face", "pleading face puppy eyes"],
  ["🥹", "face holding back tears", "face holding back tears gratitude"],
  ["😦", "frowning face with open mouth", "frowning face with open mouth"],
  ["😧", "anguished face", "anguished face stunned"],
  ["😨", "fearful face", "fearful face scared shocked oops"],
  ["😰", "anxious face with sweat", "anxious face with sweat nervous cold"],
  ["😥", "sad but relieved face", "sad but relieved face phew sweat nervous disappointed"],
  ["😢", "crying face", "crying face sad tear cry"],
  ["😭", "loudly crying face", "loudly crying face sad cry bawling sob"],
  ["😱", "face screaming in fear", "face screaming in fear horror shocked scream"],
  ["😖", "confounded face", "confounded face"],
  ["😣", "persevering face", "persevering face struggling persevere"],
  ["😞", "disappointed face", "disappointed face sad"],
  ["😓", "downcast face with sweat", "downcast face with sweat"],
  ["😩", "weary face", "weary face tired"],
  ["😫", "tired face", "tired face upset whine"],
  ["🥱", "yawning face", "yawning face"],
  ["😤", "face with steam from nose", "face with steam from nose smug triumph"],
  ["😡", "enraged face", "enraged face angry rage pout"],
  ["😠", "angry face", "angry face mad annoyed"],
  ["🤬", "face with symbols on mouth", "face with symbols on mouth foul cursing"],
  ["😈", "smiling face with horns", "smiling face with horns devil evil imp"],
  ["👿", "angry face with horns", "angry face with horns devil evil imp"],
  ["💀", "skull", "skull dead danger poison"],
  ["☠️", "skull and crossbones", "skull and crossbones danger pirate"],
  ["💩", "pile of poo", "pile of poo crap hankey poop shit"],
  ["🤡", "clown face", "clown face"],
  ["👹", "ogre", "ogre monster japanese"],
  ["👺", "goblin", "goblin japanese"],
  ["👻", "ghost", "ghost halloween"],
  ["👽", "alien", "alien ufo"],
  ["👾", "alien monster", "alien monster game retro space invader"],
  ["🤖", "robot", "robot"],
  ["😺", "grinning cat", "grinning cat smiley"],
  ["😸", "grinning cat with smiling eyes", "grinning cat with smiling eyes smile"],
  ["😹", "cat with tears of joy", "cat with tears of joy"],
  ["😻", "smiling cat with heart-eyes", "smiling cat with heart eyes"],
  ["😼", "cat with wry smile", "cat with wry smile smirk"],
  ["😽", "kissing cat", "kissing cat"],
  ["🙀", "weary cat", "weary cat horror scream"],
  ["😿", "crying cat", "crying cat sad tear face"],
  ["😾", "pouting cat", "pouting cat"],
  ["🙈", "see-no-evil monkey", "see no evil monkey blind ignore"],
  ["🙉", "hear-no-evil monkey", "hear no evil monkey deaf"],
  ["🙊", "speak-no-evil monkey", "speak no evil monkey mute hush"],
  ["💌", "love letter", "love letter email envelope"],
  ["💘", "heart with arrow", "heart with arrow love cupid"],
  ["💝", "heart with ribbon", "heart with ribbon chocolates gift"],
  ["💖", "sparkling heart", "sparkling heart"],
  ["💗", "growing heart", "growing heart heartpulse"],
  ["💓", "beating heart", "beating heart heartbeat"],
  ["💞", "revolving hearts", "revolving hearts"],
  ["💕", "two hearts", "two hearts"],
  ["💟", "heart decoration", "heart decoration"],
  ["❣️", "heart exclamation", "heart exclamation heavy"],
  ["💔", "broken heart", "broken heart"],
  ["❤️\u200d🔥", "heart on fire", "heart on fire"],
  ["❤️\u200d🩹", "mending heart", "mending heart"],
  ["❤️", "red heart", "red heart love"],
  ["🩷", "pink heart", "pink heart"],
  ["🧡", "orange heart", "orange heart"],
  ["💛", "yellow heart", "yellow heart"],
  ["💚", "green heart", "green heart"],
  ["💙", "blue heart", "blue heart"],
  ["🩵", "light blue heart", "light blue heart"],
  ["💜", "purple heart", "purple heart"],
  ["🤎", "brown heart", "brown heart"],
  ["🖤", "black heart", "black heart"],
  ["🩶", "grey heart", "grey heart"],
  ["🤍", "white heart", "white heart"],
  ["💋", "kiss mark", "kiss mark lipstick"],
  ["💯", "hundred points", "hundred points score perfect 100"],
  ["💢", "anger symbol", "anger symbol angry"],
  ["💥", "collision", "collision explode boom"],
  ["💫", "dizzy", "dizzy star"],
  ["💦", "sweat droplets", "sweat droplets water workout drops"],
  ["💨", "dashing away", "dashing away wind blow fast dash"],
  ["🕳️", "hole", "hole"],
  ["💬", "speech balloon", "speech balloon comment"],
  ["👁️\u200d🗨️", "eye in speech bubble", "eye in speech bubble"],
  ["🗨️", "left speech bubble", "left speech bubble"],
  ["🗯️", "right anger bubble", "right anger bubble"],
  ["💭", "thought balloon", "thought balloon thinking"],
  ["💤", "ZZZ", "zzz sleeping"],
  ["👋", "waving hand", "waving hand goodbye wave"],
  ["🤚", "raised back of hand", "raised back of hand"],
  ["🖐️", "hand with fingers splayed", "hand with fingers splayed raised"],
  ["✋", "raised hand", "raised hand highfive stop"],
  ["🖖", "vulcan salute", "vulcan salute prosper spock"],
  ["🫱", "rightwards hand", "rightwards hand"],
  ["🫲", "leftwards hand", "leftwards hand"],
  ["🫳", "palm down hand", "palm down hand"],
  ["🫴", "palm up hand", "palm up hand"],
  ["🫷", "leftwards pushing hand", "leftwards pushing hand"],
  ["🫸", "rightwards pushing hand", "rightwards pushing hand"],
  ["👌", "OK hand", "ok hand"],
  ["🤌", "pinched fingers", "pinched fingers"],
  ["🤏", "pinching hand", "pinching hand"],
  ["✌️", "victory hand", "victory hand peace v"],
  ["🤞", "crossed fingers", "crossed fingers luck hopeful"],
  ["🫰", "hand with index finger and thumb crossed", "hand with index finger and thumb crossed"],
  ["🤟", "love-you gesture", "love you gesture"],
  ["🤘", "sign of the horns", "sign of the horns metal"],
  ["🤙", "call me hand", "call me hand"],
  ["👈", "backhand index pointing left", "backhand index pointing left point"],
  ["👉", "backhand index pointing right", "backhand index pointing right point"],
  ["👆", "backhand index pointing up", "backhand index pointing up point 2"],
  ["🖕", "middle finger", "middle finger fu"],
  ["👇", "backhand index pointing down", "backhand index pointing down point"],
  ["☝️", "index pointing up", "index pointing up point"],
  ["🫵", "index pointing at the viewer", "index pointing at the viewer"],
  ["👍", "thumbs up", "thumbs up approve ok 1 thumbsup"],
  ["👎", "thumbs down", "thumbs down disapprove bury 1 thumbsdown"],
  ["✊", "raised fist", "raised fist power"],
  ["👊", "oncoming fist", "oncoming fist attack facepunch punch"],
  ["🤛", "left-facing fist", "left facing fist"],
  ["🤜", "right-facing fist", "right facing fist"],
  ["👏", "clapping hands", "clapping hands praise applause clap"],
  ["🙌", "raising hands", "raising hands hooray raised"],
  ["🫶", "heart hands", "heart hands love"],
  ["👐", "open hands", "open hands"],
  ["🤲", "palms up together", "palms up together"],
  ["🤝", "handshake", "handshake deal"],
  ["🙏", "folded hands", "folded hands please hope wish pray"],
  ["✍️", "writing hand", "writing hand"],
  ["💅", "nail polish", "nail polish beauty manicure care"],
  ["🤳", "selfie", "selfie"],
  ["💪", "flexed biceps", "flexed biceps flex bicep strong workout muscle"],
  ["🦾", "mechanical arm", "mechanical arm"],
  ["🦿", "mechanical leg", "mechanical leg"],
  ["🦵", "leg", "leg"],
  ["🦶", "foot", "foot"],
  ["👂", "ear", "ear hear sound listen"],
  ["🦻", "ear with hearing aid", "ear with hearing aid"],
  ["👃", "nose", "nose smell"],
  ["🧠", "brain", "brain"],
  ["🫀", "anatomical heart", "anatomical heart"],
  ["🫁", "lungs", "lungs"],
  ["🦷", "tooth", "tooth"],
  ["🦴", "bone", "bone"],
  ["👀", "eyes", "eyes look see watch"],
  ["👁️", "eye", "eye"],
  ["👅", "tongue", "tongue taste"],
  ["👄", "mouth", "mouth kiss lips"],
  ["🫦", "biting lip", "biting lip"],
  ["👶", "baby", "baby child newborn"],
  ["🧒", "child", "child"],
  ["👦", "boy", "boy child"],
  ["👧", "girl", "girl child"],
  ["🧑", "person", "person adult"],
  ["👱", "person: blond hair", "person blond hair haired"],
  ["👨", "man", "man mustache father dad"],
  ["🧔", "person: beard", "person beard bearded"],
  ["🧔\u200d♂️", "man: beard", "man beard"],
  ["🧔\u200d♀️", "woman: beard", "woman beard"],
  ["👨\u200d🦰", "man: red hair", "man red hair haired"],
  ["👨\u200d🦱", "man: curly hair", "man curly hair haired"],
  ["👨\u200d🦳", "man: white hair", "man white hair haired"],
  ["👨\u200d🦲", "man: bald", "man bald"],
  ["👩", "woman", "woman girls"],
  ["👩\u200d🦰", "woman: red hair", "woman red hair haired"],
  ["🧑\u200d🦰", "person: red hair", "person red hair"],
  ["👩\u200d🦱", "woman: curly hair", "woman curly hair haired"],
  ["🧑\u200d🦱", "person: curly hair", "person curly hair"],
  ["👩\u200d🦳", "woman: white hair", "woman white hair haired"],
  ["🧑\u200d🦳", "person: white hair", "person white hair"],
  ["👩\u200d🦲", "woman: bald", "woman bald"],
  ["🧑\u200d🦲", "person: bald", "person bald"],
  ["👱\u200d♀️", "woman: blond hair", "woman blond hair haired blonde"],
  ["👱\u200d♂️", "man: blond hair", "man blond hair haired"],
  ["🧓", "older person", "older person adult"],
  ["👴", "old man", "old man older"],
  ["👵", "old woman", "old woman older"],
  ["🙍", "person frowning", "person frowning"],
  ["🙍\u200d♂️", "man frowning", "man frowning"],
  ["🙍\u200d♀️", "woman frowning", "woman frowning"],
  ["🙎", "person pouting", "person pouting face"],
  ["🙎\u200d♂️", "man pouting", "man pouting"],
  ["🙎\u200d♀️", "woman pouting", "woman pouting"],
  ["🙅", "person gesturing NO", "person gesturing no stop halt denied good"],
  ["🙅\u200d♂️", "man gesturing NO", "man gesturing no stop halt denied good ng"],
  ["🙅\u200d♀️", "woman gesturing NO", "woman gesturing no stop halt denied good ng"],
  ["🙆", "person gesturing OK", "person gesturing ok"],
  ["🙆\u200d♂️", "man gesturing OK", "man gesturing ok"],
  ["🙆\u200d♀️", "woman gesturing OK", "woman gesturing ok"],
  ["💁", "person tipping hand", "person tipping hand information desk"],
  ["💁\u200d♂️", "man tipping hand", "man tipping hand information sassy"],
  ["💁\u200d♀️", "woman tipping hand", "woman tipping hand information sassy"],
  ["🙋", "person raising hand", "person raising hand"],
  ["🙋\u200d♂️", "man raising hand", "man raising hand"],
  ["🙋\u200d♀️", "woman raising hand", "woman raising hand"],
  ["🧏", "deaf person", "deaf person"],
  ["🧏\u200d♂️", "deaf man", "deaf man"],
  ["🧏\u200d♀️", "deaf woman", "deaf woman"],
  ["🙇", "person bowing", "person bowing respect thanks bow"],
  ["🙇\u200d♂️", "man bowing", "man bowing respect thanks"],
  ["🙇\u200d♀️", "woman bowing", "woman bowing respect thanks"],
  ["🤦", "person facepalming", "person facepalming facepalm"],
  ["🤦\u200d♂️", "man facepalming", "man facepalming"],
  ["🤦\u200d♀️", "woman facepalming", "woman facepalming"],
  ["🤷", "person shrugging", "person shrugging shrug"],
  ["🤷\u200d♂️", "man shrugging", "man shrugging"],
  ["🤷\u200d♀️", "woman shrugging", "woman shrugging"],
  ["🧑\u200d⚕️", "health worker", "health worker"],
  ["👨\u200d⚕️", "man health worker", "man health worker doctor nurse"],
  ["👩\u200d⚕️", "woman health worker", "woman health worker doctor nurse"],
  ["🧑\u200d🎓", "student", "student"],
  ["👨\u200d🎓", "man student", "man student graduation"],
  ["👩\u200d🎓", "woman student", "woman student graduation"],
  ["🧑\u200d🏫", "teacher", "teacher"],
  ["👨\u200d🏫", "man teacher", "man teacher school professor"],
  ["👩\u200d🏫", "woman teacher", "woman teacher school professor"],
  ["🧑\u200d⚖️", "judge", "judge"],
  ["👨\u200d⚖️", "man judge", "man judge justice"],
  ["👩\u200d⚖️", "woman judge", "woman judge justice"],
  ["🧑\u200d🌾", "farmer", "farmer"],
  ["👨\u200d🌾", "man farmer", "man farmer"],
  ["👩\u200d🌾", "woman farmer", "woman farmer"],
  ["🧑\u200d🍳", "cook", "cook"],
  ["👨\u200d🍳", "man cook", "man cook chef"],
  ["👩\u200d🍳", "woman cook", "woman cook chef"],
  ["🧑\u200d🔧", "mechanic", "mechanic"],
  ["👨\u200d🔧", "man mechanic", "man mechanic"],
  ["👩\u200d🔧", "woman mechanic", "woman mechanic"],
  ["🧑\u200d🏭", "factory worker", "factory worker"],
  ["👨\u200d🏭", "man factory worker", "man factory worker"],
  ["👩\u200d🏭", "woman factory worker", "woman factory worker"],
  ["🧑\u200d💼", "office worker", "office worker"],
  ["👨\u200d💼", "man office worker", "man office worker business"],
  ["👩\u200d💼", "woman office worker", "woman office worker business"],
  ["🧑\u200d🔬", "scientist", "scientist"],
  ["👨\u200d🔬", "man scientist", "man scientist research"],
  ["👩\u200d🔬", "woman scientist", "woman scientist research"],
  ["🧑\u200d💻", "technologist", "technologist"],
  ["👨\u200d💻", "man technologist", "man technologist coder"],
  ["👩\u200d💻", "woman technologist", "woman technologist coder"],
  ["🧑\u200d🎤", "singer", "singer"],
  ["👨\u200d🎤", "man singer", "man singer rockstar"],
  ["👩\u200d🎤", "woman singer", "woman singer rockstar"],
  ["🧑\u200d🎨", "artist", "artist"],
  ["👨\u200d🎨", "man artist", "man artist painter"],
  ["👩\u200d🎨", "woman artist", "woman artist painter"],
  ["🧑\u200d✈️", "pilot", "pilot"],
  ["👨\u200d✈️", "man pilot", "man pilot"],
  ["👩\u200d✈️", "woman pilot", "woman pilot"],
  ["🧑\u200d🚀", "astronaut", "astronaut"],
  ["👨\u200d🚀", "man astronaut", "man astronaut space"],
  ["👩\u200d🚀", "woman astronaut", "woman astronaut space"],
  ["🧑\u200d🚒", "firefighter", "firefighter"],
  ["👨\u200d🚒", "man firefighter", "man firefighter"],
  ["👩\u200d🚒", "woman firefighter", "woman firefighter"],
  ["👮", "police officer", "police officer law cop"],
  ["👮\u200d♂️", "man police officer", "man police officer law cop policeman"],
  ["👮\u200d♀️", "woman police officer", "woman police officer law cop policewoman"],
  ["🕵️", "detective", "detective sleuth"],
  ["🕵️\u200d♂️", "man detective", "man detective sleuth male"],
  ["🕵️\u200d♀️", "woman detective", "woman detective sleuth female"],
  ["💂", "guard", "guard"],
  ["💂\u200d♂️", "man guard", "man guard guardsman"],
  ["💂\u200d♀️", "woman guard", "woman guard guardswoman"],
  ["🥷", "ninja", "ninja"],
  ["👷", "construction worker", "construction worker helmet"],
  ["👷\u200d♂️", "man construction worker", "man construction worker helmet"],
  ["👷\u200d♀️", "woman construction worker", "woman construction worker helmet"],
  ["🫅", "person with crown", "person with crown"],
  ["🤴", "prince", "prince crown royal"],
  ["👸", "princess", "princess crown royal"],
  ["👳", "person wearing turban", "person wearing turban with"],
  ["👳\u200d♂️", "man wearing turban", "man wearing turban with"],
  ["👳\u200d♀️", "woman wearing turban", "woman wearing turban with"],
  ["👲", "person with skullcap", "person with skullcap man gua pi mao"],
  ["🧕", "woman with headscarf", "woman with headscarf hijab"],
  ["🤵", "person in tuxedo", "person in tuxedo groom marriage wedding"],
  ["🤵\u200d♂️", "man in tuxedo", "man in tuxedo"],
  ["🤵\u200d♀️", "woman in tuxedo", "woman in tuxedo"],
  ["👰", "person with veil", "person with veil marriage wedding"],
  ["👰\u200d♂️", "man with veil", "man with veil"],
  ["👰\u200d♀️", "woman with veil", "woman with veil bride"],
  ["🤰", "pregnant woman", "pregnant woman"],
  ["🫃", "pregnant man", "pregnant man"],
  ["🫄", "pregnant person", "pregnant person"],
  ["🤱", "breast-feeding", "breast feeding nursing"],
  ["👩\u200d🍼", "woman feeding baby", "woman feeding baby"],
  ["👨\u200d🍼", "man feeding baby", "man feeding baby"],
  ["🧑\u200d🍼", "person feeding baby", "person feeding baby"],
  ["👼", "baby angel", "baby angel"],
  ["🎅", "Santa Claus", "santa claus christmas"],
  ["🤶", "Mrs. Claus", "mrs claus santa"],
  ["🧑\u200d🎄", "mx claus", "mx claus"],
  ["🦸", "superhero", "superhero"],
  ["🦸\u200d♂️", "man superhero", "man superhero"],
  ["🦸\u200d♀️", "woman superhero", "woman superhero"],
  ["🦹", "supervillain", "supervillain"],
  ["🦹\u200d♂️", "man supervillain", "man supervillain"],
  ["🦹\u200d♀️", "woman supervillain", "woman supervillain"],
  ["🧙", "mage", "mage wizard"],
  ["🧙\u200d♂️", "man mage", "man mage wizard"],
  ["🧙\u200d♀️", "woman mage", "woman mage wizard"],
  ["🧚", "fairy", "fairy"],
  ["🧚\u200d♂️", "man fairy", "man fairy"],
  ["🧚\u200d♀️", "woman fairy", "woman fairy"],
  ["🧛", "vampire", "vampire"],
  ["🧛\u200d♂️", "man vampire", "man vampire"],
  ["🧛\u200d♀️", "woman vampire", "woman vampire"],
  ["🧜", "merperson", "merperson"],
  ["🧜\u200d♂️", "merman", "merman"],
  ["🧜\u200d♀️", "mermaid", "mermaid"],
  ["🧝", "elf", "elf"],
  ["🧝\u200d♂️", "man elf", "man elf"],
  ["🧝\u200d♀️", "woman elf", "woman elf"],
  ["🧞", "genie", "genie"],
  ["🧞\u200d♂️", "man genie", "man genie"],
  ["🧞\u200d♀️", "woman genie", "woman genie"],
  ["🧟", "zombie", "zombie"],
  ["🧟\u200d♂️", "man zombie", "man zombie"],
  ["🧟\u200d♀️", "woman zombie", "woman zombie"],
  ["🧌", "troll", "troll"],
  ["💆", "person getting massage", "person getting massage spa"],
  ["💆\u200d♂️", "man getting massage", "man getting massage spa"],
  ["💆\u200d♀️", "woman getting massage", "woman getting massage spa"],
  ["💇", "person getting haircut", "person getting haircut beauty"],
  ["💇\u200d♂️", "man getting haircut", "man getting haircut"],
  ["💇\u200d♀️", "woman getting haircut", "woman getting haircut"],
  ["🚶", "person walking", "person walking"],
  ["🚶\u200d♂️", "man walking", "man walking"],
  ["🚶\u200d♀️", "woman walking", "woman walking"],
  ["🧍", "person standing", "person standing"],
  ["🧍\u200d♂️", "man standing", "man standing"],
  ["🧍\u200d♀️", "woman standing", "woman standing"],
  ["🧎", "person kneeling", "person kneeling"],
  ["🧎\u200d♂️", "man kneeling", "man kneeling"],
  ["🧎\u200d♀️", "woman kneeling", "woman kneeling"],
  ["🧑\u200d🦯", "person with white cane", "person with white cane probing"],
  ["👨\u200d🦯", "man with white cane", "man with white cane probing"],
  ["👩\u200d🦯", "woman with white cane", "woman with white cane probing"],
  ["🧑\u200d🦼", "person in motorized wheelchair", "person in motorized wheelchair"],
  ["👨\u200d🦼", "man in motorized wheelchair", "man in motorized wheelchair"],
  ["👩\u200d🦼", "woman in motorized wheelchair", "woman in motorized wheelchair"],
  ["🧑\u200d🦽", "person in manual wheelchair", "person in manual wheelchair"],
  ["👨\u200d🦽", "man in manual wheelchair", "man in manual wheelchair"],
  ["👩\u200d🦽", "woman in manual wheelchair", "woman in manual wheelchair"],
  ["🏃", "person running", "person running exercise workout marathon runner"],
  ["🏃\u200d♂️", "man running", "man running exercise workout marathon"],
  ["🏃\u200d♀️", "woman running", "woman running exercise workout marathon"],
  ["💃", "woman dancing", "woman dancing dress dancer"],
  ["🕺", "man dancing", "man dancing dancer"],
  ["🕴️", "person in suit levitating", "person in suit levitating business"],
  ["👯", "people with bunny ears", "people with bunny ears dancers"],
  ["👯\u200d♂️", "men with bunny ears", "men with bunny ears dancing"],
  ["👯\u200d♀️", "women with bunny ears", "women with bunny ears dancing"],
  ["🧖", "person in steamy room", "person in steamy room sauna"],
  ["🧖\u200d♂️", "man in steamy room", "man in steamy room sauna"],
  ["🧖\u200d♀️", "woman in steamy room", "woman in steamy room sauna"],
  ["🧗", "person climbing", "person climbing bouldering"],
  ["🧗\u200d♂️", "man climbing", "man climbing bouldering"],
  ["🧗\u200d♀️", "woman climbing", "woman climbing bouldering"],
  ["🤺", "person fencing", "person fencing"],
  ["🏇", "horse racing", "horse racing"],
  ["⛷️", "skier", "skier"],
  ["🏂", "snowboarder", "snowboarder"],
  ["🏌️", "person golfing", "person golfing"],
  ["🏌️\u200d♂️", "man golfing", "man golfing"],
  ["🏌️\u200d♀️", "woman golfing", "woman golfing"],
  ["🏄", "person surfing", "person surfing surfer"],
  ["🏄\u200d♂️", "man surfing", "man surfing"],
  ["🏄\u200d♀️", "woman surfing", "woman surfing"],
  ["🚣", "person rowing boat", "person rowing boat rowboat"],
  ["🚣\u200d♂️", "man rowing boat", "man rowing boat"],
  ["🚣\u200d♀️", "woman rowing boat", "woman rowing boat"],
  ["🏊", "person swimming", "person swimming swimmer"],
  ["🏊\u200d♂️", "man swimming", "man swimming"],
  ["🏊\u200d♀️", "woman swimming", "woman swimming"],
  ["⛹️", "person bouncing ball", "person bouncing ball basketball"],
  ["⛹️\u200d♂️", "man bouncing ball", "man bouncing ball basketball"],
  ["⛹️\u200d♀️", "woman bouncing ball", "woman bouncing ball basketball"],
  ["🏋️", "person lifting weights", "person lifting weights gym workout weight"],
  ["🏋️\u200d♂️", "man lifting weights", "man lifting weights gym workout weight"],
  ["🏋️\u200d♀️", "woman lifting weights", "woman lifting weights gym workout weight"],
  ["🚴", "person biking", "person biking bicyclist"],
  ["🚴\u200d♂️", "man biking", "man biking"],
  ["🚴\u200d♀️", "woman biking", "woman biking"],
  ["🚵", "person mountain biking", "person mountain biking bicyclist"],
  ["🚵\u200d♂️", "man mountain biking", "man mountain biking"],
  ["🚵\u200d♀️", "woman mountain biking", "woman mountain biking"],
  ["🤸", "person cartwheeling", "person cartwheeling"],
  ["🤸\u200d♂️", "man cartwheeling", "man cartwheeling"],
  ["🤸\u200d♀️", "woman cartwheeling", "woman cartwheeling"],
  ["🤼", "people wrestling", "people wrestling"],
  ["🤼\u200d♂️", "men wrestling", "men wrestling"],
  ["🤼\u200d♀️", "women wrestling", "women wrestling"],
  ["🤽", "person playing water polo", "person playing water polo"],
  ["🤽\u200d♂️", "man playing water polo", "man playing water polo"],
  ["🤽\u200d♀️", "woman playing water polo", "woman playing water polo"],
  ["🤾", "person playing handball", "person playing handball"],
  ["🤾\u200d♂️", "man playing handball", "man playing handball"],
  ["🤾\u200d♀️", "woman playing handball", "woman playing handball"],
  ["🤹", "person juggling", "person juggling"],
  ["🤹\u200d♂️", "man juggling", "man juggling"],
  ["🤹\u200d♀️", "woman juggling", "woman juggling"],
  ["🧘", "person in lotus position", "person in lotus position meditation"],
  ["🧘\u200d♂️", "man in lotus position", "man in lotus position meditation"],
  ["🧘\u200d♀️", "woman in lotus position", "woman in lotus position meditation"],
  ["🛀", "person taking bath", "person taking bath shower"],
  ["🛌", "person in bed", "person in bed sleeping"],
  ["🧑\u200d🤝\u200d🧑", "people holding hands", "people holding hands couple date"],
  ["👭", "women holding hands", "women holding hands couple date two"],
  ["👫", "woman and man holding hands", "woman and man holding hands date couple"],
  ["👬", "men holding hands", "men holding hands couple date two"],
  ["💏", "kiss", "kiss couplekiss"],
  ["👩\u200d❤️\u200d💋\u200d👨", "kiss: woman, man", "kiss woman man couplekiss"],
  ["👨\u200d❤️\u200d💋\u200d👨", "kiss: man, man", "kiss man couplekiss"],
  ["👩\u200d❤️\u200d💋\u200d👩", "kiss: woman, woman", "kiss woman couplekiss"],
  ["💑", "couple with heart", "couple with heart"],
  ["👩\u200d❤️\u200d👨", "couple with heart: woman, man", "couple with heart woman man"],
  ["👨\u200d❤️\u200d👨", "couple with heart: man, man", "couple with heart man"],
  ["👩\u200d❤️\u200d👩", "couple with heart: woman, woman", "couple with heart woman"],
  ["👪", "family", "family home parents child"],
  ["👨\u200d👩\u200d👦", "family: man, woman, boy", "family man woman boy"],
  ["👨\u200d👩\u200d👧", "family: man, woman, girl", "family man woman girl"],
  ["👨\u200d👩\u200d👧\u200d👦", "family: man, woman, girl, boy", "family man woman girl boy"],
  ["👨\u200d👩\u200d👦\u200d👦", "family: man, woman, boy, boy", "family man woman boy"],
  ["👨\u200d👩\u200d👧\u200d👧", "family: man, woman, girl, girl", "family man woman girl"],
  ["👨\u200d👨\u200d👦", "family: man, man, boy", "family man boy"],
  ["👨\u200d👨\u200d👧", "family: man, man, girl", "family man girl"],
  ["👨\u200d👨\u200d👧\u200d👦", "family: man, man, girl, boy", "family man girl boy"],
  ["👨\u200d👨\u200d👦\u200d👦", "family: man, man, boy, boy", "family man boy"],
  ["👨\u200d👨\u200d👧\u200d👧", "family: man, man, girl, girl", "family man girl"],
  ["👩\u200d👩\u200d👦", "family: woman, woman, boy", "family woman boy"],
  ["👩\u200d👩\u200d👧", "family: woman, woman, girl", "family woman girl"],
  ["👩\u200d👩\u200d👧\u200d👦", "family: woman, woman, girl, boy", "family woman girl boy"],
  ["👩\u200d👩\u200d👦\u200d👦", "family: woman, woman, boy, boy", "family woman boy"],
  ["👩\u200d👩\u200d👧\u200d👧", "family: woman, woman, girl, girl", "family woman girl"],
  ["👨\u200d👦", "family: man, boy", "family man boy"],
  ["👨\u200d👦\u200d👦", "family: man, boy, boy", "family man boy"],
  ["👨\u200d👧", "family: man, girl", "family man girl"],
  ["👨\u200d👧\u200d👦", "family: man, girl, boy", "family man girl boy"],
  ["👨\u200d👧\u200d👧", "family: man, girl, girl", "family man girl"],
  ["👩\u200d👦", "family: woman, boy", "family woman boy"],
  ["👩\u200d👦\u200d👦", "family: woman, boy, boy", "family woman boy"],
  ["👩\u200d👧", "family: woman, girl", "family woman girl"],
  ["👩\u200d👧\u200d👦", "family: woman, girl, boy", "family woman girl boy"],
  ["👩\u200d👧\u200d👧", "family: woman, girl, girl", "family woman girl"],
  ["🗣️", "speaking head", "speaking head"],
  ["👤", "bust in silhouette", "bust in silhouette user"],
  ["👥", "busts in silhouette", "busts in silhouette users group team"],
  ["🫂", "people hugging", "people hugging"],
  ["👣", "footprints", "footprints feet tracks"],
  ["🐵", "monkey face", "monkey face"],
  ["🐒", "monkey", "monkey"],
  ["🦍", "gorilla", "gorilla"],
  ["🦧", "orangutan", "orangutan"],
  ["🐶", "dog face", "dog face pet"],
  ["🐕", "dog", "dog dog2"],
  ["🦮", "guide dog", "guide dog"],
  ["🐕\u200d🦺", "service dog", "service dog"],
  ["🐩", "poodle", "poodle dog"],
  ["🐺", "wolf", "wolf"],
  ["🦊", "fox", "fox face"],
  ["🦝", "raccoon", "raccoon"],
  ["🐱", "cat face", "cat face pet"],
  ["🐈", "cat", "cat cat2"],
  ["🐈\u200d⬛", "black cat", "black cat"],
  ["🦁", "lion", "lion"],
  ["🐯", "tiger face", "tiger face"],
  ["🐅", "tiger", "tiger tiger2"],
  ["🐆", "leopard", "leopard"],
  ["🐴", "horse face", "horse face"],
  ["🫎", "moose", "moose canada"],
  ["🫏", "donkey", "donkey mule"],
  ["🐎", "horse", "horse speed racehorse"],
  ["🦄", "unicorn", "unicorn"],
  ["🦓", "zebra", "zebra"],
  ["🦌", "deer", "deer"],
  ["🦬", "bison", "bison"],
  ["🐮", "cow face", "cow face"],
  ["🐂", "ox", "ox"],
  ["🐃", "water buffalo", "water buffalo"],
  ["🐄", "cow", "cow cow2"],
  ["🐷", "pig face", "pig face"],
  ["🐖", "pig", "pig pig2"],
  ["🐗", "boar", "boar"],
  ["🐽", "pig nose", "pig nose"],
  ["🐏", "ram", "ram"],
  ["🐑", "ewe", "ewe sheep"],
  ["🐐", "goat", "goat"],
  ["🐪", "camel", "camel desert dromedary"],
  ["🐫", "two-hump camel", "two hump camel"],
  ["🦙", "llama", "llama"],
  ["🦒", "giraffe", "giraffe"],
  ["🐘", "elephant", "elephant"],
  ["🦣", "mammoth", "mammoth"],
  ["🦏", "rhinoceros", "rhinoceros"],
  ["🦛", "hippopotamus", "hippopotamus"],
  ["🐭", "mouse face", "mouse face"],
  ["🐁", "mouse", "mouse mouse2"],
  ["🐀", "rat", "rat"],
  ["🐹", "hamster", "hamster pet"],
  ["🐰", "rabbit face", "rabbit face bunny"],
  ["🐇", "rabbit", "rabbit rabbit2"],
  ["🐿️", "chipmunk", "chipmunk"],
  ["🦫", "beaver", "beaver"],
  ["🦔", "hedgehog", "hedgehog"],
  ["🦇", "bat", "bat"],
  ["🐻", "bear", "bear"],
  ["🐻\u200d❄️", "polar bear", "polar bear"],
  ["🐨", "koala", "koala"],
  ["🐼", "panda", "panda face"],
  ["🦥", "sloth", "sloth"],
  ["🦦", "otter", "otter"],
  ["🦨", "skunk", "skunk"],
  ["🦘", "kangaroo", "kangaroo"],
  ["🦡", "badger", "badger"],
  ["🐾", "paw prints", "paw prints feet"],
  ["🦃", "turkey", "turkey thanksgiving"],
  ["🐔", "chicken", "chicken"],
  ["🐓", "rooster", "rooster"],
  ["🐣", "hatching chick", "hatching chick"],
  ["🐤", "baby chick", "baby chick"],
  ["🐥", "front-facing baby chick", "front facing baby chick hatched"],
  ["🐦", "bird", "bird"],
  ["🐧", "penguin", "penguin"],
  ["🕊️", "dove", "dove peace"],
  ["🦅", "eagle", "eagle"],
  ["🦆", "duck", "duck"],
  ["🦢", "swan", "swan"],
  ["🦉", "owl", "owl"],
  ["🦤", "dodo", "dodo"],
  ["🪶", "feather", "feather"],
  ["🦩", "flamingo", "flamingo"],
  ["🦚", "peacock", "peacock"],
  ["🦜", "parrot", "parrot"],
  ["🪽", "wing", "wing fly"],
  ["🐦\u200d⬛", "black bird", "black bird"],
  ["🪿", "goose", "goose honk"],
  ["🐸", "frog", "frog"],
  ["🐊", "crocodile", "crocodile"],
  ["🐢", "turtle", "turtle slow"],
  ["🦎", "lizard", "lizard"],
  ["🐍", "snake", "snake"],
  ["🐲", "dragon face", "dragon face"],
  ["🐉", "dragon", "dragon"],
  ["🦕", "sauropod", "sauropod dinosaur"],
  ["🦖", "T-Rex", "t rex dinosaur"],
  ["🐳", "spouting whale", "spouting whale sea"],
  ["🐋", "whale", "whale whale2"],
  ["🐬", "dolphin", "dolphin flipper"],
  ["🦭", "seal", "seal"],
  ["🐟", "fish", "fish"],
  ["🐠", "tropical fish", "tropical fish"],
  ["🐡", "blowfish", "blowfish"],
  ["🦈", "shark", "shark"],
  ["🐙", "octopus", "octopus"],
  ["🐚", "spiral shell", "spiral shell sea beach"],
  ["🪸", "coral", "coral"],
  ["🪼", "jellyfish", "jellyfish"],
  ["🐌", "snail", "snail slow"],
  ["🦋", "butterfly", "butterfly"],
  ["🐛", "bug", "bug"],
  ["🐜", "ant", "ant"],
  ["🐝", "honeybee", "honeybee bee"],
  ["🪲", "beetle", "beetle"],
  ["🐞", "lady beetle", "lady beetle bug"],
  ["🦗", "cricket", "cricket"],
  ["🪳", "cockroach", "cockroach"],
  ["🕷️", "spider", "spider"],
  ["🕸️", "spider web", "spider web"],
  ["🦂", "scorpion", "scorpion"],
  ["🦟", "mosquito", "mosquito"],
  ["🪰", "fly", "fly"],
  ["🪱", "worm", "worm"],
  ["🦠", "microbe", "microbe germ"],
  ["💐", "bouquet", "bouquet flowers"],
  ["🌸", "cherry blossom", "cherry blossom flower spring"],
  ["💮", "white flower", "white flower"],
  ["🪷", "lotus", "lotus"],
  ["🏵️", "rosette", "rosette"],
  ["🌹", "rose", "rose flower"],
  ["🥀", "wilted flower", "wilted flower"],
  ["🌺", "hibiscus", "hibiscus"],
  ["🌻", "sunflower", "sunflower"],
  ["🌼", "blossom", "blossom"],
  ["🌷", "tulip", "tulip flower"],
  ["🪻", "hyacinth", "hyacinth"],
  ["🌱", "seedling", "seedling plant"],
  ["🪴", "potted plant", "potted plant"],
  ["🌲", "evergreen tree", "evergreen tree wood"],
  ["🌳", "deciduous tree", "deciduous tree wood"],
  ["🌴", "palm tree", "palm tree"],
  ["🌵", "cactus", "cactus"],
  ["🌾", "sheaf of rice", "sheaf of rice ear"],
  ["🌿", "herb", "herb"],
  ["☘️", "shamrock", "shamrock"],
  ["🍀", "four leaf clover", "four leaf clover luck"],
  ["🍁", "maple leaf", "maple leaf canada"],
  ["🍂", "fallen leaf", "fallen leaf autumn"],
  ["🍃", "leaf fluttering in wind", "leaf fluttering in wind leaves"],
  ["🪹", "empty nest", "empty nest"],
  ["🪺", "nest with eggs", "nest with eggs"],
  ["🍄", "mushroom", "mushroom fungus"],
  ["🍇", "grapes", "grapes"],
  ["🍈", "melon", "melon"],
  ["🍉", "watermelon", "watermelon"],
  ["🍊", "tangerine", "tangerine orange mandarin"],
  ["🍋", "lemon", "lemon"],
  ["🍌", "banana", "banana fruit"],
  ["🍍", "pineapple", "pineapple"],
  ["🥭", "mango", "mango"],
  ["🍎", "red apple", "red apple"],
  ["🍏", "green apple", "green apple fruit"],
  ["🍐", "pear", "pear"],
  ["🍑", "peach", "peach"],
  ["🍒", "cherries", "cherries fruit"],
  ["🍓", "strawberry", "strawberry fruit"],
  ["🫐", "blueberries", "blueberries"],
  ["🥝", "kiwi fruit", "kiwi fruit"],
  ["🍅", "tomato", "tomato"],
  ["🫒", "olive", "olive"],
  ["🥥", "coconut", "coconut"],
  ["🥑", "avocado", "avocado"],
  ["🍆", "eggplant", "eggplant aubergine"],
  ["🥔", "potato", "potato"],
  ["🥕", "carrot", "carrot"],
  ["🌽", "ear of corn", "ear of corn"],
  ["🌶️", "hot pepper", "hot pepper spicy"],
  ["🫑", "bell pepper", "bell pepper"],
  ["🥒", "cucumber", "cucumber"],
  ["🥬", "leafy green", "leafy green"],
  ["🥦", "broccoli", "broccoli"],
  ["🧄", "garlic", "garlic"],
  ["🧅", "onion", "onion"],
  ["🥜", "peanuts", "peanuts"],
  ["🫘", "beans", "beans"],
  ["🌰", "chestnut", "chestnut"],
  ["🫚", "ginger root", "ginger root"],
  ["🫛", "pea pod", "pea pod"],
  ["🍞", "bread", "bread toast"],
  ["🥐", "croissant", "croissant"],
  ["🥖", "baguette bread", "baguette bread"],
  ["🫓", "flatbread", "flatbread"],
  ["🥨", "pretzel", "pretzel"],
  ["🥯", "bagel", "bagel"],
  ["🥞", "pancakes", "pancakes"],
  ["🧇", "waffle", "waffle"],
  ["🧀", "cheese wedge", "cheese wedge"],
  ["🍖", "meat on bone", "meat on bone"],
  ["🍗", "poultry leg", "poultry leg meat chicken"],
  ["🥩", "cut of meat", "cut of meat"],
  ["🥓", "bacon", "bacon"],
  ["🍔", "hamburger", "hamburger burger"],
  ["🍟", "french fries", "french fries"],
  ["🍕", "pizza", "pizza"],
  ["🌭", "hot dog", "hot dog hotdog"],
  ["🥪", "sandwich", "sandwich"],
  ["🌮", "taco", "taco"],
  ["🌯", "burrito", "burrito"],
  ["🫔", "tamale", "tamale"],
  ["🥙", "stuffed flatbread", "stuffed flatbread"],
  ["🧆", "falafel", "falafel"],
  ["🥚", "egg", "egg"],
  ["🍳", "cooking", "cooking breakfast fried egg"],
  ["🥘", "shallow pan of food", "shallow pan of food paella curry"],
  ["🍲", "pot of food", "pot of food stew"],
  ["🫕", "fondue", "fondue"],
  ["🥣", "bowl with spoon", "bowl with spoon"],
  ["🥗", "green salad", "green salad"],
  ["🍿", "popcorn", "popcorn"],
  ["🧈", "butter", "butter"],
  ["🧂", "salt", "salt"],
  ["🥫", "canned food", "canned food"],
  ["🍱", "bento box", "bento box"],
  ["🍘", "rice cracker", "rice cracker"],
  ["🍙", "rice ball", "rice ball"],
  ["🍚", "cooked rice", "cooked rice"],
  ["🍛", "curry rice", "curry rice"],
  ["🍜", "steaming bowl", "steaming bowl noodle ramen"],
  ["🍝", "spaghetti", "spaghetti pasta"],
  ["🍠", "roasted sweet potato", "roasted sweet potato"],
  ["🍢", "oden", "oden"],
  ["🍣", "sushi", "sushi"],
  ["🍤", "fried shrimp", "fried shrimp tempura"],
  ["🍥", "fish cake with swirl", "fish cake with swirl"],
  ["🥮", "moon cake", "moon cake"],
  ["🍡", "dango", "dango"],
  ["🥟", "dumpling", "dumpling"],
  ["🥠", "fortune cookie", "fortune cookie"],
  ["🥡", "takeout box", "takeout box"],
  ["🦀", "crab", "crab"],
  ["🦞", "lobster", "lobster"],
  ["🦐", "shrimp", "shrimp"],
  ["🦑", "squid", "squid"],
  ["🦪", "oyster", "oyster"],
  ["🍦", "soft ice cream", "soft ice cream icecream"],
  ["🍧", "shaved ice", "shaved ice"],
  ["🍨", "ice cream", "ice cream"],
  ["🍩", "doughnut", "doughnut"],
  ["🍪", "cookie", "cookie"],
  ["🎂", "birthday cake", "birthday cake party"],
  ["🍰", "shortcake", "shortcake dessert cake"],
  ["🧁", "cupcake", "cupcake"],
  ["🥧", "pie", "pie"],
  ["🍫", "chocolate bar", "chocolate bar"],
  ["🍬", "candy", "candy sweet"],
  ["🍭", "lollipop", "lollipop"],
  ["🍮", "custard", "custard"],
  ["🍯", "honey pot", "honey pot"],
  ["🍼", "baby bottle", "baby bottle milk"],
  ["🥛", "glass of milk", "glass of milk"],
  ["☕", "hot beverage", "hot beverage cafe espresso coffee"],
  ["🫖", "teapot", "teapot"],
  ["🍵", "teacup without handle", "teacup without handle green breakfast tea"],
  ["🍶", "sake", "sake"],
  ["🍾", "bottle with popping cork", "bottle with popping cork bubbly celebration champagne"],
  ["🍷", "wine glass", "wine glass"],
  ["🍸", "cocktail glass", "cocktail glass drink"],
  ["🍹", "tropical drink", "tropical drink summer vacation"],
  ["🍺", "beer mug", "beer mug drink"],
  ["🍻", "clinking beer mugs", "clinking beer mugs drinks beers"],
  ["🥂", "clinking glasses", "clinking glasses cheers toast"],
  ["🥃", "tumbler glass", "tumbler glass whisky"],
  ["🫗", "pouring liquid", "pouring liquid"],
  ["🥤", "cup with straw", "cup with straw"],
  ["🧋", "bubble tea", "bubble tea"],
  ["🧃", "beverage box", "beverage box"],
  ["🧉", "mate", "mate"],
  ["🧊", "ice", "ice cube"],
  ["🥢", "chopsticks", "chopsticks"],
  ["🍽️", "fork and knife with plate", "fork and knife with plate dining dinner cutlery"],
  ["🍴", "fork and knife", "fork and knife cutlery"],
  ["🥄", "spoon", "spoon"],
  ["🔪", "kitchen knife", "kitchen knife cut chop hocho"],
  ["🫙", "jar", "jar"],
  ["🏺", "amphora", "amphora"],
  ["🌍", "globe showing Europe-Africa", "globe showing europe africa world international earth"],
  ["🌎", "globe showing Americas", "globe showing americas world international earth"],
  ["🌏", "globe showing Asia-Australia", "globe showing asia australia world international earth"],
  ["🌐", "globe with meridians", "globe with meridians world global international"],
  ["🗺️", "world map", "world map travel"],
  ["🗾", "map of Japan", "map of japan"],
  ["🧭", "compass", "compass"],
  ["🏔️", "snow-capped mountain", "snow capped mountain"],
  ["⛰️", "mountain", "mountain"],
  ["🌋", "volcano", "volcano"],
  ["🗻", "mount fuji", "mount fuji"],
  ["🏕️", "camping", "camping"],
  ["🏖️", "beach with umbrella", "beach with umbrella"],
  ["🏜️", "desert", "desert"],
  ["🏝️", "desert island", "desert island"],
  ["🏞️", "national park", "national park"],
  ["🏟️", "stadium", "stadium"],
  ["🏛️", "classical building", "classical building"],
  ["🏗️", "building construction", "building construction"],
  ["🧱", "brick", "brick bricks"],
  ["🪨", "rock", "rock"],
  ["🪵", "wood", "wood"],
  ["🛖", "hut", "hut"],
  ["🏘️", "houses", "houses"],
  ["🏚️", "derelict house", "derelict house"],
  ["🏠", "house", "house"],
  ["🏡", "house with garden", "house with garden"],
  ["🏢", "office building", "office building"],
  ["🏣", "Japanese post office", "japanese post office"],
  ["🏤", "post office", "post office european"],
  ["🏥", "hospital", "hospital"],
  ["🏦", "bank", "bank"],
  ["🏨", "hotel", "hotel"],
  ["🏩", "love hotel", "love hotel"],
  ["🏪", "convenience store", "convenience store"],
  ["🏫", "school", "school"],
  ["🏬", "department store", "department store"],
  ["🏭", "factory", "factory"],
  ["🏯", "Japanese castle", "japanese castle"],
  ["🏰", "castle", "castle european"],
  ["💒", "wedding", "wedding marriage"],
  ["🗼", "Tokyo tower", "tokyo tower"],
  ["🗽", "Statue of Liberty", "statue of liberty"],
  ["⛪", "church", "church"],
  ["🕌", "mosque", "mosque"],
  ["🛕", "hindu temple", "hindu temple"],
  ["🕍", "synagogue", "synagogue"],
  ["⛩️", "shinto shrine", "shinto shrine"],
  ["🕋", "kaaba", "kaaba"],
  ["⛲", "fountain", "fountain"],
  ["⛺", "tent", "tent camping"],
  ["🌁", "foggy", "foggy karl"],
  ["🌃", "night with stars", "night with stars"],
  ["🏙️", "cityscape", "cityscape skyline"],
  ["🌄", "sunrise over mountains", "sunrise over mountains"],
  ["🌅", "sunrise", "sunrise"],
  ["🌆", "cityscape at dusk", "cityscape at dusk city sunset"],
  ["🌇", "sunset", "sunset city sunrise"],
  ["🌉", "bridge at night", "bridge at night"],
  ["♨️", "hot springs", "hot springs hotsprings"],
  ["🎠", "carousel horse", "carousel horse"],
  ["🛝", "playground slide", "playground slide"],
  ["🎡", "ferris wheel", "ferris wheel"],
  ["🎢", "roller coaster", "roller coaster"],
  ["💈", "barber pole", "barber pole"],
  ["🎪", "circus tent", "circus tent"],
  ["🚂", "locomotive", "locomotive train steam"],
  ["🚃", "railway car", "railway car"],
  ["🚄", "high-speed train", "high speed train bullettrain side"],
  ["🚅", "bullet train", "bullet train bullettrain front"],
  ["🚆", "train", "train train2"],
  ["🚇", "metro", "metro"],
  ["🚈", "light rail", "light rail"],
  ["🚉", "station", "station"],
  ["🚊", "tram", "tram"],
  ["🚝", "monorail", "monorail"],
  ["🚞", "mountain railway", "mountain railway"],
  ["🚋", "tram car", "tram car train"],
  ["🚌", "bus", "bus"],
  ["🚍", "oncoming bus", "oncoming bus"],
  ["🚎", "trolleybus", "trolleybus"],
  ["🚐", "minibus", "minibus"],
  ["🚑", "ambulance", "ambulance"],
  ["🚒", "fire engine", "fire engine"],
  ["🚓", "police car", "police car"],
  ["🚔", "oncoming police car", "oncoming police car"],
  ["🚕", "taxi", "taxi"],
  ["🚖", "oncoming taxi", "oncoming taxi"],
  ["🚗", "automobile", "automobile car red"],
  ["🚘", "oncoming automobile", "oncoming automobile"],
  ["🚙", "sport utility vehicle", "sport utility vehicle blue car"],
  ["🛻", "pickup truck", "pickup truck"],
  ["🚚", "delivery truck", "delivery truck"],
  ["🚛", "articulated lorry", "articulated lorry"],
  ["🚜", "tractor", "tractor"],
  ["🏎️", "racing car", "racing car"],
  ["🏍️", "motorcycle", "motorcycle"],
  ["🛵", "motor scooter", "motor scooter"],
  ["🦽", "manual wheelchair", "manual wheelchair"],
  ["🦼", "motorized wheelchair", "motorized wheelchair"],
  ["🛺", "auto rickshaw", "auto rickshaw"],
  ["🚲", "bicycle", "bicycle bike"],
  ["🛴", "kick scooter", "kick scooter"],
  ["🛹", "skateboard", "skateboard"],
  ["🛼", "roller skate", "roller skate"],
  ["🚏", "bus stop", "bus stop busstop"],
  ["🛣️", "motorway", "motorway"],
  ["🛤️", "railway track", "railway track"],
  ["🛢️", "oil drum", "oil drum"],
  ["⛽", "fuel pump", "fuel pump fuelpump"],
  ["🛞", "wheel", "wheel"],
  ["🚨", "police car light", "police car light 911 emergency rotating"],
  ["🚥", "horizontal traffic light", "horizontal traffic light"],
  ["🚦", "vertical traffic light", "vertical traffic light semaphore"],
  ["🛑", "stop sign", "stop sign"],
  ["🚧", "construction", "construction wip"],
  ["⚓", "anchor", "anchor ship"],
  ["🛟", "ring buoy", "ring buoy life preserver"],
  ["⛵", "sailboat", "sailboat boat"],
  ["🛶", "canoe", "canoe"],
  ["🚤", "speedboat", "speedboat ship"],
  ["🛳️", "passenger ship", "passenger ship cruise"],
  ["⛴️", "ferry", "ferry"],
  ["🛥️", "motor boat", "motor boat"],
  ["🚢", "ship", "ship"],
  ["✈️", "airplane", "airplane flight"],
  ["🛩️", "small airplane", "small airplane flight"],
  ["🛫", "airplane departure", "airplane departure flight"],
  ["🛬", "airplane arrival", "airplane arrival flight"],
  ["🪂", "parachute", "parachute"],
  ["💺", "seat", "seat"],
  ["🚁", "helicopter", "helicopter"],
  ["🚟", "suspension railway", "suspension railway"],
  ["🚠", "mountain cableway", "mountain cableway"],
  ["🚡", "aerial tramway", "aerial tramway"],
  ["🛰️", "satellite", "satellite orbit space artificial"],
  ["🚀", "rocket", "rocket ship launch"],
  ["🛸", "flying saucer", "flying saucer ufo"],
  ["🛎️", "bellhop bell", "bellhop bell"],
  ["🧳", "luggage", "luggage"],
  ["⌛", "hourglass done", "hourglass done time"],
  ["⏳", "hourglass not done", "hourglass not done time flowing sand"],
  ["⌚", "watch", "watch time"],
  ["⏰", "alarm clock", "alarm clock morning"],
  ["⏱️", "stopwatch", "stopwatch"],
  ["⏲️", "timer clock", "timer clock"],
  ["🕰️", "mantelpiece clock", "mantelpiece clock"],
  ["🕛", "twelve o’clock", "twelve oclock clock12"],
  ["🕧", "twelve-thirty", "twelve thirty clock1230"],
  ["🕐", "one o’clock", "one oclock clock1"],
  ["🕜", "one-thirty", "one thirty clock130"],
  ["🕑", "two o’clock", "two oclock clock2"],
  ["🕝", "two-thirty", "two thirty clock230"],
  ["🕒", "three o’clock", "three oclock clock3"],
  ["🕞", "three-thirty", "three thirty clock330"],
  ["🕓", "four o’clock", "four oclock clock4"],
  ["🕟", "four-thirty", "four thirty clock430"],
  ["🕔", "five o’clock", "five oclock clock5"],
  ["🕠", "five-thirty", "five thirty clock530"],
  ["🕕", "six o’clock", "six oclock clock6"],
  ["🕡", "six-thirty", "six thirty clock630"],
  ["🕖", "seven o’clock", "seven oclock clock7"],
  ["🕢", "seven-thirty", "seven thirty clock730"],
  ["🕗", "eight o’clock", "eight oclock clock8"],
  ["🕣", "eight-thirty", "eight thirty clock830"],
  ["🕘", "nine o’clock", "nine oclock clock9"],
  ["🕤", "nine-thirty", "nine thirty clock930"],
  ["🕙", "ten o’clock", "ten oclock clock10"],
  ["🕥", "ten-thirty", "ten thirty clock1030"],
  ["🕚", "eleven o’clock", "eleven oclock clock11"],
  ["🕦", "eleven-thirty", "eleven thirty clock1130"],
  ["🌑", "new moon", "new moon"],
  ["🌒", "waxing crescent moon", "waxing crescent moon"],
  ["🌓", "first quarter moon", "first quarter moon"],
  ["🌔", "waxing gibbous moon", "waxing gibbous moon"],
  ["🌕", "full moon", "full moon"],
  ["🌖", "waning gibbous moon", "waning gibbous moon"],
  ["🌗", "last quarter moon", "last quarter moon"],
  ["🌘", "waning crescent moon", "waning crescent moon"],
  ["🌙", "crescent moon", "crescent moon night"],
  ["🌚", "new moon face", "new moon face with"],
  ["🌛", "first quarter moon face", "first quarter moon face with"],
  ["🌜", "last quarter moon face", "last quarter moon face with"],
  ["🌡️", "thermometer", "thermometer"],
  ["☀️", "sun", "sun weather sunny"],
  ["🌝", "full moon face", "full moon face with"],
  ["🌞", "sun with face", "sun with face summer"],
  ["🪐", "ringed planet", "ringed planet"],
  ["⭐", "star", "star"],
  ["🌟", "glowing star", "glowing star star2"],
  ["🌠", "shooting star", "shooting star stars"],
  ["🌌", "milky way", "milky way"],
  ["☁️", "cloud", "cloud"],
  ["⛅", "sun behind cloud", "sun behind cloud weather partly sunny"],
  ["⛈️", "cloud with lightning and rain", "cloud with lightning and rain"],
  ["🌤️", "sun behind small cloud", "sun behind small cloud"],
  ["🌥️", "sun behind large cloud", "sun behind large cloud"],
  ["🌦️", "sun behind rain cloud", "sun behind rain cloud"],
  ["🌧️", "cloud with rain", "cloud with rain"],
  ["🌨️", "cloud with snow", "cloud with snow"],
  ["🌩️", "cloud with lightning", "cloud with lightning"],
  ["🌪️", "tornado", "tornado"],
  ["🌫️", "fog", "fog"],
  ["🌬️", "wind face", "wind face"],
  ["🌀", "cyclone", "cyclone swirl"],
  ["🌈", "rainbow", "rainbow"],
  ["🌂", "closed umbrella", "closed umbrella weather rain"],
  ["☂️", "umbrella", "umbrella open"],
  ["☔", "umbrella with rain drops", "umbrella with rain drops weather"],
  ["⛱️", "umbrella on ground", "umbrella on ground beach parasol"],
  ["⚡", "high voltage", "high voltage lightning thunder zap"],
  ["❄️", "snowflake", "snowflake winter cold weather"],
  ["☃️", "snowman", "snowman winter christmas with snow"],
  ["⛄", "snowman without snow", "snowman without snow winter"],
  ["☄️", "comet", "comet"],
  ["🔥", "fire", "fire burn"],
  ["💧", "droplet", "droplet water"],
  ["🌊", "water wave", "water wave sea ocean"],
  ["🎃", "jack-o-lantern", "jack o lantern halloween"],
  ["🎄", "Christmas tree", "christmas tree"],
  ["🎆", "fireworks", "fireworks festival celebration"],
  ["🎇", "sparkler", "sparkler"],
  ["🧨", "firecracker", "firecracker"],
  ["✨", "sparkles", "sparkles shiny"],
  ["🎈", "balloon", "balloon party birthday"],
  ["🎉", "party popper", "party popper hooray tada"],
  ["🎊", "confetti ball", "confetti ball"],
  ["🎋", "tanabata tree", "tanabata tree"],
  ["🎍", "pine decoration", "pine decoration bamboo"],
  ["🎎", "Japanese dolls", "japanese dolls"],
  ["🎏", "carp streamer", "carp streamer flags"],
  ["🎐", "wind chime", "wind chime"],
  ["🎑", "moon viewing ceremony", "moon viewing ceremony rice scene"],
  ["🧧", "red envelope", "red envelope"],
  ["🎀", "ribbon", "ribbon"],
  ["🎁", "wrapped gift", "wrapped gift present birthday christmas"],
  ["🎗️", "reminder ribbon", "reminder ribbon"],
  ["🎟️", "admission tickets", "admission tickets"],
  ["🎫", "ticket", "ticket"],
  ["🎖️", "military medal", "military medal"],
  ["🏆", "trophy", "trophy award contest winner"],
  ["🏅", "sports medal", "sports medal gold winner"],
  ["🥇", "1st place medal", "1st place medal gold"],
  ["🥈", "2nd place medal", "2nd place medal silver"],
  ["🥉", "3rd place medal", "3rd place medal bronze"],
  ["⚽", "soccer ball", "soccer ball sports"],
  ["⚾", "baseball", "baseball sports"],
  ["🥎", "softball", "softball"],
  ["🏀", "basketball", "basketball sports"],
  ["🏐", "volleyball", "volleyball"],
  ["🏈", "american football", "american football sports"],
  ["🏉", "rugby football", "rugby football"],
  ["🎾", "tennis", "tennis sports"],
  ["🥏", "flying disc", "flying disc"],
  ["🎳", "bowling", "bowling"],
  ["🏏", "cricket game", "cricket game"],
  ["🏑", "field hockey", "field hockey"],
  ["🏒", "ice hockey", "ice hockey"],
  ["🥍", "lacrosse", "lacrosse"],
  ["🏓", "ping pong", "ping pong"],
  ["🏸", "badminton", "badminton"],
  ["🥊", "boxing glove", "boxing glove"],
  ["🥋", "martial arts uniform", "martial arts uniform"],
  ["🥅", "goal net", "goal net"],
  ["⛳", "flag in hole", "flag in hole golf"],
  ["⛸️", "ice skate", "ice skate skating"],
  ["🎣", "fishing pole", "fishing pole and fish"],
  ["🤿", "diving mask", "diving mask"],
  ["🎽", "running shirt", "running shirt marathon with sash"],
  ["🎿", "skis", "skis ski"],
  ["🛷", "sled", "sled"],
  ["🥌", "curling stone", "curling stone"],
  ["🎯", "bullseye", "bullseye target dart"],
  ["🪀", "yo-yo", "yo"],
  ["🪁", "kite", "kite"],
  ["🔫", "water pistol", "water pistol shoot weapon gun"],
  ["🎱", "pool 8 ball", "pool 8 ball billiards 8ball"],
  ["🔮", "crystal ball", "crystal ball fortune"],
  ["🪄", "magic wand", "magic wand"],
  ["🎮", "video game", "video game play controller console"],
  ["🕹️", "joystick", "joystick"],
  ["🎰", "slot machine", "slot machine"],
  ["🎲", "game die", "game die dice gambling"],
  ["🧩", "puzzle piece", "puzzle piece jigsaw"],
  ["🧸", "teddy bear", "teddy bear"],
  ["🪅", "piñata", "piata pinata"],
  ["🪩", "mirror ball", "mirror ball disco party"],
  ["🪆", "nesting dolls", "nesting dolls"],
  ["♠️", "spade suit", "spade suit spades"],
  ["♥️", "heart suit", "heart suit hearts"],
  ["♦️", "diamond suit", "diamond suit diamonds"],
  ["♣️", "club suit", "club suit clubs"],
  ["♟️", "chess pawn", "chess pawn"],
  ["🃏", "joker", "joker black"],
  ["🀄", "mahjong red dragon", "mahjong red dragon"],
  ["🎴", "flower playing cards", "flower playing cards"],
  ["🎭", "performing arts", "performing arts theater drama"],
  ["🖼️", "framed picture", "framed picture"],
  ["🎨", "artist palette", "artist palette design paint art"],
  ["🧵", "thread", "thread"],
  ["🪡", "sewing needle", "sewing needle"],
  ["🧶", "yarn", "yarn"],
  ["🪢", "knot", "knot"],
  ["👓", "glasses", "glasses eyeglasses"],
  ["🕶️", "sunglasses", "sunglasses dark"],
  ["🥽", "goggles", "goggles"],
  ["🥼", "lab coat", "lab coat"],
  ["🦺", "safety vest", "safety vest"],
  ["👔", "necktie", "necktie shirt formal"],
  ["👕", "t-shirt", "t shirt tshirt"],
  ["👖", "jeans", "jeans pants"],
  ["🧣", "scarf", "scarf"],
  ["🧤", "gloves", "gloves"],
  ["🧥", "coat", "coat"],
  ["🧦", "socks", "socks"],
  ["👗", "dress", "dress"],
  ["👘", "kimono", "kimono"],
  ["🥻", "sari", "sari"],
  ["🩱", "one-piece swimsuit", "one piece swimsuit"],
  ["🩲", "briefs", "briefs swim brief"],
  ["🩳", "shorts", "shorts"],
  ["👙", "bikini", "bikini beach"],
  ["👚", "woman’s clothes", "womans clothes"],
  ["🪭", "folding hand fan", "folding hand fan sensu"],
  ["👛", "purse", "purse"],
  ["👜", "handbag", "handbag bag"],
  ["👝", "clutch bag", "clutch bag pouch"],
  ["🛍️", "shopping bags", "shopping bags"],
  ["🎒", "backpack", "backpack school satchel"],
  ["🩴", "thong sandal", "thong sandal"],
  ["👞", "man’s shoe", "mans shoe"],
  ["👟", "running shoe", "running shoe sneaker sport athletic"],
  ["🥾", "hiking boot", "hiking boot"],
  ["🥿", "flat shoe", "flat shoe"],
  ["👠", "high-heeled shoe", "high heeled shoe heel"],
  ["👡", "woman’s sandal", "womans sandal shoe"],
  ["🩰", "ballet shoes", "ballet shoes"],
  ["👢", "woman’s boot", "womans boot"],
  ["🪮", "hair pick", "hair pick"],
  ["👑", "crown", "crown king queen royal"],
  ["👒", "woman’s hat", "womans hat"],
  ["🎩", "top hat", "top hat classy tophat"],
  ["🎓", "graduation cap", "graduation cap education college university mortar board"],
  ["🧢", "billed cap", "billed cap"],
  ["🪖", "military helmet", "military helmet"],
  ["⛑️", "rescue worker’s helmet", "rescue workers helmet worker"],
  ["📿", "prayer beads", "prayer beads"],
  ["💄", "lipstick", "lipstick makeup"],
  ["💍", "ring", "ring wedding marriage engaged"],
  ["💎", "gem stone", "gem stone diamond"],
  ["🔇", "muted speaker", "muted speaker sound volume mute"],
  ["🔈", "speaker low volume", "speaker low volume"],
  ["🔉", "speaker medium volume", "speaker medium volume sound"],
  ["🔊", "speaker high volume", "speaker high volume loud sound"],
  ["📢", "loudspeaker", "loudspeaker announcement"],
  ["📣", "megaphone", "megaphone mega"],
  ["📯", "postal horn", "postal horn"],
  ["🔔", "bell", "bell sound notification"],
  ["🔕", "bell with slash", "bell with slash volume off no"],
  ["🎼", "musical score", "musical score"],
  ["🎵", "musical note", "musical note"],
  ["🎶", "musical notes", "musical notes music"],
  ["🎙️", "studio microphone", "studio microphone podcast"],
  ["🎚️", "level slider", "level slider"],
  ["🎛️", "control knobs", "control knobs"],
  ["🎤", "microphone", "microphone sing"],
  ["🎧", "headphone", "headphone music earphones headphones"],
  ["📻", "radio", "radio podcast"],
  ["🎷", "saxophone", "saxophone"],
  ["🪗", "accordion", "accordion"],
  ["🎸", "guitar", "guitar rock"],
  ["🎹", "musical keyboard", "musical keyboard piano"],
  ["🎺", "trumpet", "trumpet"],
  ["🎻", "violin", "violin"],
  ["🪕", "banjo", "banjo"],
  ["🥁", "drum", "drum"],
  ["🪘", "long drum", "long drum"],
  ["🪇", "maracas", "maracas shaker"],
  ["🪈", "flute", "flute recorder"],
  ["📱", "mobile phone", "mobile phone smartphone iphone"],
  ["📲", "mobile phone with arrow", "mobile phone with arrow call incoming calling"],
  ["☎️", "telephone", "telephone phone"],
  ["📞", "telephone receiver", "telephone receiver phone call"],
  ["📟", "pager", "pager"],
  ["📠", "fax machine", "fax machine"],
  ["🔋", "battery", "battery power"],
  ["🪫", "low battery", "low battery"],
  ["🔌", "electric plug", "electric plug"],
  ["💻", "laptop", "laptop desktop screen computer"],
  ["🖥️", "desktop computer", "desktop computer"],
  ["🖨️", "printer", "printer"],
  ["⌨️", "keyboard", "keyboard"],
  ["🖱️", "computer mouse", "computer mouse"],
  ["🖲️", "trackball", "trackball"],
  ["💽", "computer disk", "computer disk minidisc"],
  ["💾", "floppy disk", "floppy disk save"],
  ["💿", "optical disk", "optical disk cd"],
  ["📀", "dvd", "dvd"],
  ["🧮", "abacus", "abacus"],
  ["🎥", "movie camera", "movie camera film video"],
  ["🎞️", "film frames", "film frames strip"],
  ["📽️", "film projector", "film projector"],
  ["🎬", "clapper board", "clapper board film"],
  ["📺", "television", "television tv"],
  ["📷", "camera", "camera photo"],
  ["📸", "camera with flash", "camera with flash photo"],
  ["📹", "video camera", "video camera"],
  ["📼", "videocassette", "videocassette vhs"],
  ["🔍", "magnifying glass tilted left", "magnifying glass tilted left search zoom mag"],
  ["🔎", "magnifying glass tilted right", "magnifying glass tilted right mag"],
  ["🕯️", "candle", "candle"],
  ["💡", "light bulb", "light bulb idea"],
  ["🔦", "flashlight", "flashlight"],
  ["🏮", "red paper lantern", "red paper lantern izakaya"],
  ["🪔", "diya lamp", "diya lamp"],
  ["📔", "notebook with decorative cover", "notebook with decorative cover"],
  ["📕", "closed book", "closed book"],
  ["📖", "open book", "open book"],
  ["📗", "green book", "green book"],
  ["📘", "blue book", "blue book"],
  ["📙", "orange book", "orange book"],
  ["📚", "books", "books library"],
  ["📓", "notebook", "notebook"],
  ["📒", "ledger", "ledger"],
  ["📃", "page with curl", "page with curl"],
  ["📜", "scroll", "scroll document"],
  ["📄", "page facing up", "page facing up document"],
  ["📰", "newspaper", "newspaper press"],
  ["🗞️", "rolled-up newspaper", "rolled up newspaper press roll"],
  ["📑", "bookmark tabs", "bookmark tabs"],
  ["🔖", "bookmark", "bookmark"],
  ["🏷️", "label", "label tag"],
  ["💰", "money bag", "money bag dollar cream moneybag"],
  ["🪙", "coin", "coin"],
  ["💴", "yen banknote", "yen banknote"],
  ["💵", "dollar banknote", "dollar banknote money"],
  ["💶", "euro banknote", "euro banknote"],
  ["💷", "pound banknote", "pound banknote"],
  ["💸", "money with wings", "money with wings dollar"],
  ["💳", "credit card", "credit card subscription"],
  ["🧾", "receipt", "receipt"],
  ["💹", "chart increasing with yen", "chart increasing with yen"],
  ["✉️", "envelope", "envelope letter email"],
  ["📧", "e-mail", "e mail email"],
  ["📨", "incoming envelope", "incoming envelope"],
  ["📩", "envelope with arrow", "envelope with arrow"],
  ["📤", "outbox tray", "outbox tray"],
  ["📥", "inbox tray", "inbox tray"],
  ["📦", "package", "package shipping"],
  ["📫", "closed mailbox with raised flag", "closed mailbox with raised flag"],
  ["📪", "closed mailbox with lowered flag", "closed mailbox with lowered flag"],
  ["📬", "open mailbox with raised flag", "open mailbox with raised flag mail"],
  ["📭", "open mailbox with lowered flag", "open mailbox with lowered flag no mail"],
  ["📮", "postbox", "postbox"],
  ["🗳️", "ballot box with ballot", "ballot box with"],
  ["✏️", "pencil", "pencil pencil2"],
  ["✒️", "black nib", "black nib"],
  ["🖋️", "fountain pen", "fountain pen"],
  ["🖊️", "pen", "pen"],
  ["🖌️", "paintbrush", "paintbrush"],
  ["🖍️", "crayon", "crayon"],
  ["📝", "memo", "memo document note pencil"],
  ["💼", "briefcase", "briefcase business"],
  ["📁", "file folder", "file folder directory"],
  ["📂", "open file folder", "open file folder"],
  ["🗂️", "card index dividers", "card index dividers"],
  ["📅", "calendar", "calendar schedule date"],
  ["📆", "tear-off calendar", "tear off calendar schedule"],
  ["🗒️", "spiral notepad", "spiral notepad"],
  ["🗓️", "spiral calendar", "spiral calendar"],
  ["📇", "card index", "card index"],
  ["📈", "chart increasing", "chart increasing graph metrics with upwards trend"],
  ["📉", "chart decreasing", "chart decreasing graph metrics with downwards trend"],
  ["📊", "bar chart", "bar chart stats metrics"],
  ["📋", "clipboard", "clipboard"],
  ["📌", "pushpin", "pushpin location"],
  ["📍", "round pushpin", "round pushpin location"],
  ["📎", "paperclip", "paperclip"],
  ["🖇️", "linked paperclips", "linked paperclips"],
  ["📏", "straight ruler", "straight ruler"],
  ["📐", "triangular ruler", "triangular ruler"],
  ["✂️", "scissors", "scissors cut"],
  ["🗃️", "card file box", "card file box"],
  ["🗄️", "file cabinet", "file cabinet"],
  ["🗑️", "wastebasket", "wastebasket trash"],
  ["🔒", "locked", "locked security private lock"],
  ["🔓", "unlocked", "unlocked security unlock"],
  ["🔏", "locked with pen", "locked with pen lock ink"],
  ["🔐", "locked with key", "locked with key security closed lock"],
  ["🔑", "key", "key lock password"],
  ["🗝️", "old key", "old key"],
  ["🔨", "hammer", "hammer tool"],
  ["🪓", "axe", "axe"],
  ["⛏️", "pick", "pick"],
  ["⚒️", "hammer and pick", "hammer and pick"],
  ["🛠️", "hammer and wrench", "hammer and wrench"],
  ["🗡️", "dagger", "dagger"],
  ["⚔️", "crossed swords", "crossed swords"],
  ["💣", "bomb", "bomb boom"],
  ["🪃", "boomerang", "boomerang"],
  ["🏹", "bow and arrow", "bow and arrow archery"],
  ["🛡️", "shield", "shield"],
  ["🪚", "carpentry saw", "carpentry saw"],
  ["🔧", "wrench", "wrench tool"],
  ["🪛", "screwdriver", "screwdriver"],
  ["🔩", "nut and bolt", "nut and bolt"],
  ["⚙️", "gear", "gear"],
  ["🗜️", "clamp", "clamp"],
  ["⚖️", "balance scale", "balance scale"],
  ["🦯", "white cane", "white cane probing"],
  ["🔗", "link", "link"],
  ["⛓️", "chains", "chains"],
  ["🪝", "hook", "hook"],
  ["🧰", "toolbox", "toolbox"],
  ["🧲", "magnet", "magnet"],
  ["🪜", "ladder", "ladder"],
  ["⚗️", "alembic", "alembic"],
  ["🧪", "test tube", "test tube"],
  ["🧫", "petri dish", "petri dish"],
  ["🧬", "dna", "dna"],
  ["🔬", "microscope", "microscope science laboratory investigate"],
  ["🔭", "telescope", "telescope"],
  ["📡", "satellite antenna", "satellite antenna signal"],
  ["💉", "syringe", "syringe health hospital needle"],
  ["🩸", "drop of blood", "drop of blood"],
  ["💊", "pill", "pill health medicine"],
  ["🩹", "adhesive bandage", "adhesive bandage"],
  ["🩼", "crutch", "crutch"],
  ["🩺", "stethoscope", "stethoscope"],
  ["🩻", "x-ray", "x ray"],
  ["🚪", "door", "door"],
  ["🛗", "elevator", "elevator"],
  ["🪞", "mirror", "mirror"],
  ["🪟", "window", "window"],
  ["🛏️", "bed", "bed"],
  ["🛋️", "couch and lamp", "couch and lamp"],
  ["🪑", "chair", "chair"],
  ["🚽", "toilet", "toilet wc"],
  ["🪠", "plunger", "plunger"],
  ["🚿", "shower", "shower bath"],
  ["🛁", "bathtub", "bathtub"],
  ["🪤", "mouse trap", "mouse trap"],
  ["🪒", "razor", "razor"],
  ["🧴", "lotion bottle", "lotion bottle"],
  ["🧷", "safety pin", "safety pin"],
  ["🧹", "broom", "broom"],
  ["🧺", "basket", "basket"],
  ["🧻", "roll of paper", "roll of paper toilet"],
  ["🪣", "bucket", "bucket"],
  ["🧼", "soap", "soap"],
  ["🫧", "bubbles", "bubbles"],
  ["🪥", "toothbrush", "toothbrush"],
  ["🧽", "sponge", "sponge"],
  ["🧯", "fire extinguisher", "fire extinguisher"],
  ["🛒", "shopping cart", "shopping cart"],
  ["🚬", "cigarette", "cigarette smoking"],
  ["⚰️", "coffin", "coffin funeral"],
  ["🪦", "headstone", "headstone"],
  ["⚱️", "funeral urn", "funeral urn"],
  ["🧿", "nazar amulet", "nazar amulet"],
  ["🪬", "hamsa", "hamsa"],
  ["🗿", "moai", "moai stone moyai"],
  ["🪧", "placard", "placard"],
  ["🪪", "identification card", "identification card"],
  ["🏧", "ATM sign", "atm sign"],
  ["🚮", "litter in bin sign", "litter in bin sign put its place"],
  ["🚰", "potable water", "potable water"],
  ["♿", "wheelchair symbol", "wheelchair symbol accessibility"],
  ["🚹", "men’s room", "mens room"],
  ["🚺", "women’s room", "womens room"],
  ["🚻", "restroom", "restroom toilet"],
  ["🚼", "baby symbol", "baby symbol"],
  ["🚾", "water closet", "water closet toilet restroom wc"],
  ["🛂", "passport control", "passport control"],
  ["🛃", "customs", "customs"],
  ["🛄", "baggage claim", "baggage claim airport"],
  ["🛅", "left luggage", "left luggage"],
  ["⚠️", "warning", "warning wip"],
  ["🚸", "children crossing", "children crossing"],
  ["⛔", "no entry", "no entry limit"],
  ["🚫", "prohibited", "prohibited block forbidden no entry sign"],
  ["🚳", "no bicycles", "no bicycles"],
  ["🚭", "no smoking", "no smoking"],
  ["🚯", "no littering", "no littering do not litter"],
  ["🚱", "non-potable water", "non potable water"],
  ["🚷", "no pedestrians", "no pedestrians"],
  ["📵", "no mobile phones", "no mobile phones"],
  ["🔞", "no one under eighteen", "no one under eighteen underage"],
  ["☢️", "radioactive", "radioactive"],
  ["☣️", "biohazard", "biohazard"],
  ["⬆️", "up arrow", "up arrow"],
  ["↗️", "up-right arrow", "up right arrow upper"],
  ["➡️", "right arrow", "right arrow"],
  ["↘️", "down-right arrow", "down right arrow lower"],
  ["⬇️", "down arrow", "down arrow"],
  ["↙️", "down-left arrow", "down left arrow lower"],
  ["⬅️", "left arrow", "left arrow"],
  ["↖️", "up-left arrow", "up left arrow upper"],
  ["↕️", "up-down arrow", "up down arrow"],
  ["↔️", "left-right arrow", "left right arrow"],
  ["↩️", "right arrow curving left", "right arrow curving left return leftwards with hook"],
  ["↪️", "left arrow curving right", "left arrow curving right hook"],
  ["⤴️", "right arrow curving up", "right arrow curving up heading"],
  ["⤵️", "right arrow curving down", "right arrow curving down heading"],
  ["🔃", "clockwise vertical arrows", "clockwise vertical arrows"],
  ["🔄", "counterclockwise arrows button", "counterclockwise arrows button sync"],
  ["🔙", "BACK arrow", "back arrow"],
  ["🔚", "END arrow", "end arrow"],
  ["🔛", "ON! arrow", "on arrow"],
  ["🔜", "SOON arrow", "soon arrow"],
  ["🔝", "TOP arrow", "top arrow"],
  ["🛐", "place of worship", "place of worship"],
  ["⚛️", "atom symbol", "atom symbol"],
  ["🕉️", "om", "om"],
  ["✡️", "star of David", "star of david"],
  ["☸️", "wheel of dharma", "wheel of dharma"],
  ["☯️", "yin yang", "yin yang"],
  ["✝️", "latin cross", "latin cross"],
  ["☦️", "orthodox cross", "orthodox cross"],
  ["☪️", "star and crescent", "star and crescent"],
  ["☮️", "peace symbol", "peace symbol"],
  ["🕎", "menorah", "menorah"],
  ["🔯", "dotted six-pointed star", "dotted six pointed star"],
  ["🪯", "khanda", "khanda"],
  ["♈", "Aries", "aries"],
  ["♉", "Taurus", "taurus"],
  ["♊", "Gemini", "gemini"],
  ["♋", "Cancer", "cancer"],
  ["♌", "Leo", "leo"],
  ["♍", "Virgo", "virgo"],
  ["♎", "Libra", "libra"],
  ["♏", "Scorpio", "scorpio scorpius"],
  ["♐", "Sagittarius", "sagittarius"],
  ["♑", "Capricorn", "capricorn"],
  ["♒", "Aquarius", "aquarius"],
  ["♓", "Pisces", "pisces"],
  ["⛎", "Ophiuchus", "ophiuchus"],
  ["🔀", "shuffle tracks button", "shuffle tracks button twisted rightwards arrows"],
  ["🔁", "repeat button", "repeat button loop"],
  ["🔂", "repeat single button", "repeat single button one"],
  ["▶️", "play button", "play button arrow forward"],
  ["⏩", "fast-forward button", "fast forward button"],
  ["⏭️", "next track button", "next track button"],
  ["⏯️", "play or pause button", "play or pause button"],
  ["◀️", "reverse button", "reverse button arrow backward"],
  ["⏪", "fast reverse button", "fast reverse button rewind"],
  ["⏮️", "last track button", "last track button previous"],
  ["🔼", "upwards button", "upwards button arrow up small"],
  ["⏫", "fast up button", "fast up button arrow double"],
  ["🔽", "downwards button", "downwards button arrow down small"],
  ["⏬", "fast down button", "fast down button arrow double"],
  ["⏸️", "pause button", "pause button"],
  ["⏹️", "stop button", "stop button"],
  ["⏺️", "record button", "record button"],
  ["⏏️", "eject button", "eject button"],
  ["🎦", "cinema", "cinema film movie"],
  ["🔅", "dim button", "dim button low brightness"],
  ["🔆", "bright button", "bright button high brightness"],
  ["📶", "antenna bars", "antenna bars wifi signal strength"],
  ["🛜", "wireless", "wireless wifi"],
  ["📳", "vibration mode", "vibration mode"],
  ["📴", "mobile phone off", "mobile phone off mute"],
  ["♀️", "female sign", "female sign"],
  ["♂️", "male sign", "male sign"],
  ["⚧️", "transgender symbol", "transgender symbol"],
  ["✖️", "multiply", "multiply heavy multiplication x"],
  ["➕", "plus", "plus heavy sign"],
  ["➖", "minus", "minus heavy sign"],
  ["➗", "divide", "divide heavy division sign"],
  ["🟰", "heavy equals sign", "heavy equals sign"],
  ["♾️", "infinity", "infinity"],
  ["‼️", "double exclamation mark", "double exclamation mark bangbang"],
  ["⁉️", "exclamation question mark", "exclamation question mark interrobang"],
  ["❓", "red question mark", "red question mark confused"],
  ["❔", "white question mark", "white question mark grey"],
  ["❕", "white exclamation mark", "white exclamation mark grey"],
  ["❗", "red exclamation mark", "red exclamation mark bang heavy"],
  ["〰️", "wavy dash", "wavy dash"],
  ["💱", "currency exchange", "currency exchange"],
  ["💲", "heavy dollar sign", "heavy dollar sign"],
  ["⚕️", "medical symbol", "medical symbol"],
  ["♻️", "recycling symbol", "recycling symbol environment green recycle"],
  ["⚜️", "fleur-de-lis", "fleur de lis"],
  ["🔱", "trident emblem", "trident emblem"],
  ["📛", "name badge", "name badge"],
  ["🔰", "Japanese symbol for beginner", "japanese symbol for beginner"],
  ["⭕", "hollow red circle", "hollow red circle o"],
  ["✅", "check mark button", "check mark button white"],
  ["☑️", "check box with check", "check box with ballot"],
  ["✔️", "check mark", "check mark heavy"],
  ["❌", "cross mark", "cross mark x"],
  ["❎", "cross mark button", "cross mark button negative squared"],
  ["➰", "curly loop", "curly loop"],
  ["➿", "double curly loop", "double curly loop"],
  ["〽️", "part alternation mark", "part alternation mark"],
  ["✳️", "eight-spoked asterisk", "eight spoked asterisk"],
  ["✴️", "eight-pointed star", "eight pointed star black"],
  ["❇️", "sparkle", "sparkle"],
  ["©️", "copyright", "copyright"],
  ["®️", "registered", "registered"],
  ["™️", "trade mark", "trade mark trademark tm"],
  ["#️⃣", "keycap: #", "keycap number hash"],
  ["*️⃣", "keycap: *", "keycap asterisk"],
  ["0️⃣", "keycap: 0", "keycap 0 zero"],
  ["1️⃣", "keycap: 1", "keycap 1 one"],
  ["2️⃣", "keycap: 2", "keycap 2 two"],
  ["3️⃣", "keycap: 3", "keycap 3 three"],
  ["4️⃣", "keycap: 4", "keycap 4 four"],
  ["5️⃣", "keycap: 5", "keycap 5 five"],
  ["6️⃣", "keycap: 6", "keycap 6 six"],
  ["7️⃣", "keycap: 7", "keycap 7 seven"],
  ["8️⃣", "keycap: 8", "keycap 8 eight"],
  ["9️⃣", "keycap: 9", "keycap 9 nine"],
  ["🔟", "keycap: 10", "keycap 10 ten"],
  ["🔠", "input latin uppercase", "input latin uppercase letters capital abcd"],
  ["🔡", "input latin lowercase", "input latin lowercase abcd"],
  ["🔢", "input numbers", "input numbers 1234"],
  ["🔣", "input symbols", "input symbols"],
  ["🔤", "input latin letters", "input latin letters alphabet abc"],
  ["🅰️", "A button (blood type)", "a button blood type"],
  ["🆎", "AB button (blood type)", "ab button blood type"],
  ["🅱️", "B button (blood type)", "b button blood type"],
  ["🆑", "CL button", "cl button"],
  ["🆒", "COOL button", "cool button"],
  ["🆓", "FREE button", "free button"],
  ["ℹ️", "information", "information source"],
  ["🆔", "ID button", "id button"],
  ["Ⓜ️", "circled M", "circled m"],
  ["🆕", "NEW button", "new button fresh"],
  ["🆖", "NG button", "ng button"],
  ["🅾️", "O button (blood type)", "o button blood type o2"],
  ["🆗", "OK button", "ok button yes"],
  ["🅿️", "P button", "p button parking"],
  ["🆘", "SOS button", "sos button help emergency"],
  ["🆙", "UP! button", "up button"],
  ["🆚", "VS button", "vs button"],
  ["🈁", "Japanese “here” button", "japanese here button koko"],
  ["🈂️", "Japanese “service charge” button", "japanese service charge button sa"],
  ["🈷️", "Japanese “monthly amount” button", "japanese monthly amount button u6708"],
  ["🈶", "Japanese “not free of charge” button", "japanese not free of charge button u6709"],
  ["🈯", "Japanese “reserved” button", "japanese reserved button u6307"],
  ["🉐", "Japanese “bargain” button", "japanese bargain button ideograph advantage"],
  ["🈹", "Japanese “discount” button", "japanese discount button u5272"],
  ["🈚", "Japanese “free of charge” button", "japanese free of charge button u7121"],
  ["🈲", "Japanese “prohibited” button", "japanese prohibited button u7981"],
  ["🉑", "Japanese “acceptable” button", "japanese acceptable button accept"],
  ["🈸", "Japanese “application” button", "japanese application button u7533"],
  ["🈴", "Japanese “passing grade” button", "japanese passing grade button u5408"],
  ["🈳", "Japanese “vacancy” button", "japanese vacancy button u7a7a"],
  ["㊗️", "Japanese “congratulations” button", "japanese congratulations button"],
  ["㊙️", "Japanese “secret” button", "japanese secret button"],
  ["🈺", "Japanese “open for business” button", "japanese open for business button u55b6"],
  ["🈵", "Japanese “no vacancy” button", "japanese no vacancy button u6e80"],
  ["🔴", "red circle", "red circle"],
  ["🟠", "orange circle", "orange circle"],
  ["🟡", "yellow circle", "yellow circle"],
  ["🟢", "green circle", "green circle"],
  ["🔵", "blue circle", "blue circle large"],
  ["🟣", "purple circle", "purple circle"],
  ["🟤", "brown circle", "brown circle"],
  ["⚫", "black circle", "black circle"],
  ["⚪", "white circle", "white circle"],
  ["🟥", "red square", "red square"],
  ["🟧", "orange square", "orange square"],
  ["🟨", "yellow square", "yellow square"],
  ["🟩", "green square", "green square"],
  ["🟦", "blue square", "blue square"],
  ["🟪", "purple square", "purple square"],
  ["🟫", "brown square", "brown square"],
  ["⬛", "black large square", "black large square"],
  ["⬜", "white large square", "white large square"],
  ["◼️", "black medium square", "black medium square"],
  ["◻️", "white medium square", "white medium square"],
  ["◾", "black medium-small square", "black medium small square"],
  ["◽", "white medium-small square", "white medium small square"],
  ["▪️", "black small square", "black small square"],
  ["▫️", "white small square", "white small square"],
  ["🔶", "large orange diamond", "large orange diamond"],
  ["🔷", "large blue diamond", "large blue diamond"],
  ["🔸", "small orange diamond", "small orange diamond"],
  ["🔹", "small blue diamond", "small blue diamond"],
  ["🔺", "red triangle pointed up", "red triangle pointed up small"],
  ["🔻", "red triangle pointed down", "red triangle pointed down small"],
  ["💠", "diamond with a dot", "diamond with a dot shape inside"],
  ["🔘", "radio button", "radio button"],
  ["🔳", "white square button", "white square button"],
  ["🔲", "black square button", "black square button"],
  ["🏁", "chequered flag", "chequered flag milestone finish checkered"],
  ["🚩", "triangular flag", "triangular flag on post"],
  ["🎌", "crossed flags", "crossed flags"],
  ["🏴", "black flag", "black flag"],
  ["🏳️", "white flag", "white flag"],
  ["🏳️\u200d🌈", "rainbow flag", "rainbow flag pride"],
  ["🏳️\u200d⚧️", "transgender flag", "transgender flag"],
  ["🏴\u200d☠️", "pirate flag", "pirate flag"],
  ["🇦🇨", "flag: Ascension Island", "flag ascension island"],
  ["🇦🇩", "flag: Andorra", "flag andorra"],
  ["🇦🇪", "flag: United Arab Emirates", "flag united arab emirates"],
  ["🇦🇫", "flag: Afghanistan", "flag afghanistan"],
  ["🇦🇬", "flag: Antigua & Barbuda", "flag antigua barbuda"],
  ["🇦🇮", "flag: Anguilla", "flag anguilla"],
  ["🇦🇱", "flag: Albania", "flag albania"],
  ["🇦🇲", "flag: Armenia", "flag armenia"],
  ["🇦🇴", "flag: Angola", "flag angola"],
  ["🇦🇶", "flag: Antarctica", "flag antarctica"],
  ["🇦🇷", "flag: Argentina", "flag argentina"],
  ["🇦🇸", "flag: American Samoa", "flag american samoa"],
  ["🇦🇹", "flag: Austria", "flag austria"],
  ["🇦🇺", "flag: Australia", "flag australia"],
  ["🇦🇼", "flag: Aruba", "flag aruba"],
  ["🇦🇽", "flag: Åland Islands", "flag land islands aland"],
  ["🇦🇿", "flag: Azerbaijan", "flag azerbaijan"],
  ["🇧🇦", "flag: Bosnia & Herzegovina", "flag bosnia herzegovina"],
  ["🇧🇧", "flag: Barbados", "flag barbados"],
  ["🇧🇩", "flag: Bangladesh", "flag bangladesh"],
  ["🇧🇪", "flag: Belgium", "flag belgium"],
  ["🇧🇫", "flag: Burkina Faso", "flag burkina faso"],
  ["🇧🇬", "flag: Bulgaria", "flag bulgaria"],
  ["🇧🇭", "flag: Bahrain", "flag bahrain"],
  ["🇧🇮", "flag: Burundi", "flag burundi"],
  ["🇧🇯", "flag: Benin", "flag benin"],
  ["🇧🇱", "flag: St. Barthélemy", "flag st barthlemy barthelemy"],
  ["🇧🇲", "flag: Bermuda", "flag bermuda"],
  ["🇧🇳", "flag: Brunei", "flag brunei"],
  ["🇧🇴", "flag: Bolivia", "flag bolivia"],
  ["🇧🇶", "flag: Caribbean Netherlands", "flag caribbean netherlands"],
  ["🇧🇷", "flag: Brazil", "flag brazil"],
  ["🇧🇸", "flag: Bahamas", "flag bahamas"],
  ["🇧🇹", "flag: Bhutan", "flag bhutan"],
  ["🇧🇻", "flag: Bouvet Island", "flag bouvet island"],
  ["🇧🇼", "flag: Botswana", "flag botswana"],
  ["🇧🇾", "flag: Belarus", "flag belarus"],
  ["🇧🇿", "flag: Belize", "flag belize"],
  ["🇨🇦", "flag: Canada", "flag canada"],
  ["🇨🇨", "flag: Cocos (Keeling) Islands", "flag cocos keeling islands"],
  ["🇨🇩", "flag: Congo - Kinshasa", "flag congo kinshasa"],
  ["🇨🇫", "flag: Central African Republic", "flag central african republic"],
  ["🇨🇬", "flag: Congo - Brazzaville", "flag congo brazzaville"],
  ["🇨🇭", "flag: Switzerland", "flag switzerland"],
  ["🇨🇮", "flag: Côte d’Ivoire", "flag cte divoire ivory cote"],
  ["🇨🇰", "flag: Cook Islands", "flag cook islands"],
  ["🇨🇱", "flag: Chile", "flag chile"],
  ["🇨🇲", "flag: Cameroon", "flag cameroon"],
  ["🇨🇳", "flag: China", "flag china cn"],
  ["🇨🇴", "flag: Colombia", "flag colombia"],
  ["🇨🇵", "flag: Clipperton Island", "flag clipperton island"],
  ["🇨🇷", "flag: Costa Rica", "flag costa rica"],
  ["🇨🇺", "flag: Cuba", "flag cuba"],
  ["🇨🇻", "flag: Cape Verde", "flag cape verde"],
  ["🇨🇼", "flag: Curaçao", "flag curaao curacao"],
  ["🇨🇽", "flag: Christmas Island", "flag christmas island"],
  ["🇨🇾", "flag: Cyprus", "flag cyprus"],
  ["🇨🇿", "flag: Czechia", "flag czechia czech republic"],
  ["🇩🇪", "flag: Germany", "flag germany de"],
  ["🇩🇬", "flag: Diego Garcia", "flag diego garcia"],
  ["🇩🇯", "flag: Djibouti", "flag djibouti"],
  ["🇩🇰", "flag: Denmark", "flag denmark"],
  ["🇩🇲", "flag: Dominica", "flag dominica"],
  ["🇩🇴", "flag: Dominican Republic", "flag dominican republic"],
  ["🇩🇿", "flag: Algeria", "flag algeria"],
  ["🇪🇦", "flag: Ceuta & Melilla", "flag ceuta melilla"],
  ["🇪🇨", "flag: Ecuador", "flag ecuador"],
  ["🇪🇪", "flag: Estonia", "flag estonia"],
  ["🇪🇬", "flag: Egypt", "flag egypt"],
  ["🇪🇭", "flag: Western Sahara", "flag western sahara"],
  ["🇪🇷", "flag: Eritrea", "flag eritrea"],
  ["🇪🇸", "flag: Spain", "flag spain es"],
  ["🇪🇹", "flag: Ethiopia", "flag ethiopia"],
  ["🇪🇺", "flag: European Union", "flag european union eu"],
  ["🇫🇮", "flag: Finland", "flag finland"],
  ["🇫🇯", "flag: Fiji", "flag fiji"],
  ["🇫🇰", "flag: Falkland Islands", "flag falkland islands"],
  ["🇫🇲", "flag: Micronesia", "flag micronesia"],
  ["🇫🇴", "flag: Faroe Islands", "flag faroe islands"],
  ["🇫🇷", "flag: France", "flag france french fr"],
  ["🇬🇦", "flag: Gabon", "flag gabon"],
  ["🇬🇧", "flag: United Kingdom", "flag united kingdom british gb uk"],
  ["🇬🇩", "flag: Grenada", "flag grenada"],
  ["🇬🇪", "flag: Georgia", "flag georgia"],
  ["🇬🇫", "flag: French Guiana", "flag french guiana"],
  ["🇬🇬", "flag: Guernsey", "flag guernsey"],
  ["🇬🇭", "flag: Ghana", "flag ghana"],
  ["🇬🇮", "flag: Gibraltar", "flag gibraltar"],
  ["🇬🇱", "flag: Greenland", "flag greenland"],
  ["🇬🇲", "flag: Gambia", "flag gambia"],
  ["🇬🇳", "flag: Guinea", "flag guinea"],
  ["🇬🇵", "flag: Guadeloupe", "flag guadeloupe"],
  ["🇬🇶", "flag: Equatorial Guinea", "flag equatorial guinea"],
  ["🇬🇷", "flag: Greece", "flag greece"],
  ["🇬🇸", "flag: South Georgia & South Sandwich Islands", "flag south georgia sandwich islands"],
  ["🇬🇹", "flag: Guatemala", "flag guatemala"],
  ["🇬🇺", "flag: Guam", "flag guam"],
  ["🇬🇼", "flag: Guinea-Bissau", "flag guinea bissau"],
  ["🇬🇾", "flag: Guyana", "flag guyana"],
  ["🇭🇰", "flag: Hong Kong SAR China", "flag hong kong sar china"],
  ["🇭🇲", "flag: Heard & McDonald Islands", "flag heard mcdonald islands"],
  ["🇭🇳", "flag: Honduras", "flag honduras"],
  ["🇭🇷", "flag: Croatia", "flag croatia"],
  ["🇭🇹", "flag: Haiti", "flag haiti"],
  ["🇭🇺", "flag: Hungary", "flag hungary"],
  ["🇮🇨", "flag: Canary Islands", "flag canary islands"],
  ["🇮🇩", "flag: Indonesia", "flag indonesia"],
  ["🇮🇪", "flag: Ireland", "flag ireland"],
  ["🇮🇱", "flag: Israel", "flag israel"],
  ["🇮🇲", "flag: Isle of Man", "flag isle of man"],
  ["🇮🇳", "flag: India", "flag india"],
  ["🇮🇴", "flag: British Indian Ocean Territory", "flag british indian ocean territory"],
  ["🇮🇶", "flag: Iraq", "flag iraq"],
  ["🇮🇷", "flag: Iran", "flag iran"],
  ["🇮🇸", "flag: Iceland", "flag iceland"],
  ["🇮🇹", "flag: Italy", "flag italy it"],
  ["🇯🇪", "flag: Jersey", "flag jersey"],
  ["🇯🇲", "flag: Jamaica", "flag jamaica"],
  ["🇯🇴", "flag: Jordan", "flag jordan"],
  ["🇯🇵", "flag: Japan", "flag japan jp"],
  ["🇰🇪", "flag: Kenya", "flag kenya"],
  ["🇰🇬", "flag: Kyrgyzstan", "flag kyrgyzstan"],
  ["🇰🇭", "flag: Cambodia", "flag cambodia"],
  ["🇰🇮", "flag: Kiribati", "flag kiribati"],
  ["🇰🇲", "flag: Comoros", "flag comoros"],
  ["🇰🇳", "flag: St. Kitts & Nevis", "flag st kitts nevis"],
  ["🇰🇵", "flag: North Korea", "flag north korea"],
  ["🇰🇷", "flag: South Korea", "flag south korea kr"],
  ["🇰🇼", "flag: Kuwait", "flag kuwait"],
  ["🇰🇾", "flag: Cayman Islands", "flag cayman islands"],
  ["🇰🇿", "flag: Kazakhstan", "flag kazakhstan"],
  ["🇱🇦", "flag: Laos", "flag laos"],
  ["🇱🇧", "flag: Lebanon", "flag lebanon"],
  ["🇱🇨", "flag: St. Lucia", "flag st lucia"],
  ["🇱🇮", "flag: Liechtenstein", "flag liechtenstein"],
  ["🇱🇰", "flag: Sri Lanka", "flag sri lanka"],
  ["🇱🇷", "flag: Liberia", "flag liberia"],
  ["🇱🇸", "flag: Lesotho", "flag lesotho"],
  ["🇱🇹", "flag: Lithuania", "flag lithuania"],
  ["🇱🇺", "flag: Luxembourg", "flag luxembourg"],
  ["🇱🇻", "flag: Latvia", "flag latvia"],
  ["🇱🇾", "flag: Libya", "flag libya"],
  ["🇲🇦", "flag: Morocco", "flag morocco"],
  ["🇲🇨", "flag: Monaco", "flag monaco"],
  ["🇲🇩", "flag: Moldova", "flag moldova"],
  ["🇲🇪", "flag: Montenegro", "flag montenegro"],
  ["🇲🇫", "flag: St. Martin", "flag st martin"],
  ["🇲🇬", "flag: Madagascar", "flag madagascar"],
  ["🇲🇭", "flag: Marshall Islands", "flag marshall islands"],
  ["🇲🇰", "flag: North Macedonia", "flag north macedonia"],
  ["🇲🇱", "flag: Mali", "flag mali"],
  ["🇲🇲", "flag: Myanmar (Burma)", "flag myanmar burma"],
  ["🇲🇳", "flag: Mongolia", "flag mongolia"],
  ["🇲🇴", "flag: Macao SAR China", "flag macao sar china macau"],
  ["🇲🇵", "flag: Northern Mariana Islands", "flag northern mariana islands"],
  ["🇲🇶", "flag: Martinique", "flag martinique"],
  ["🇲🇷", "flag: Mauritania", "flag mauritania"],
  ["🇲🇸", "flag: Montserrat", "flag montserrat"],
  ["🇲🇹", "flag: Malta", "flag malta"],
  ["🇲🇺", "flag: Mauritius", "flag mauritius"],
  ["🇲🇻", "flag: Maldives", "flag maldives"],
  ["🇲🇼", "flag: Malawi", "flag malawi"],
  ["🇲🇽", "flag: Mexico", "flag mexico"],
  ["🇲🇾", "flag: Malaysia", "flag malaysia"],
  ["🇲🇿", "flag: Mozambique", "flag mozambique"],
  ["🇳🇦", "flag: Namibia", "flag namibia"],
  ["🇳🇨", "flag: New Caledonia", "flag new caledonia"],
  ["🇳🇪", "flag: Niger", "flag niger"],
  ["🇳🇫", "flag: Norfolk Island", "flag norfolk island"],
  ["🇳🇬", "flag: Nigeria", "flag nigeria"],
  ["🇳🇮", "flag: Nicaragua", "flag nicaragua"],
  ["🇳🇱", "flag: Netherlands", "flag netherlands"],
  ["🇳🇴", "flag: Norway", "flag norway"],
  ["🇳🇵", "flag: Nepal", "flag nepal"],
  ["🇳🇷", "flag: Nauru", "flag nauru"],
  ["🇳🇺", "flag: Niue", "flag niue"],
  ["🇳🇿", "flag: New Zealand", "flag new zealand"],
  ["🇴🇲", "flag: Oman", "flag oman"],
  ["🇵🇦", "flag: Panama", "flag panama"],
  ["🇵🇪", "flag: Peru", "flag peru"],
  ["🇵🇫", "flag: French Polynesia", "flag french polynesia"],
  ["🇵🇬", "flag: Papua New Guinea", "flag papua new guinea"],
  ["🇵🇭", "flag: Philippines", "flag philippines"],
  ["🇵🇰", "flag: Pakistan", "flag pakistan"],
  ["🇵🇱", "flag: Poland", "flag poland"],
  ["🇵🇲", "flag: St. Pierre & Miquelon", "flag st pierre miquelon"],
  ["🇵🇳", "flag: Pitcairn Islands", "flag pitcairn islands"],
  ["🇵🇷", "flag: Puerto Rico", "flag puerto rico"],
  ["🇵🇸", "flag: Palestinian Territories", "flag palestinian territories"],
  ["🇵🇹", "flag: Portugal", "flag portugal"],
  ["🇵🇼", "flag: Palau", "flag palau"],
  ["🇵🇾", "flag: Paraguay", "flag paraguay"],
  ["🇶🇦", "flag: Qatar", "flag qatar"],
  ["🇷🇪", "flag: Réunion", "flag runion reunion"],
  ["🇷🇴", "flag: Romania", "flag romania"],
  ["🇷🇸", "flag: Serbia", "flag serbia"],
  ["🇷🇺", "flag: Russia", "flag russia ru"],
  ["🇷🇼", "flag: Rwanda", "flag rwanda"],
  ["🇸🇦", "flag: Saudi Arabia", "flag saudi arabia"],
  ["🇸🇧", "flag: Solomon Islands", "flag solomon islands"],
  ["🇸🇨", "flag: Seychelles", "flag seychelles"],
  ["🇸🇩", "flag: Sudan", "flag sudan"],
  ["🇸🇪", "flag: Sweden", "flag sweden"],
  ["🇸🇬", "flag: Singapore", "flag singapore"],
  ["🇸🇭", "flag: St. Helena", "flag st helena"],
  ["🇸🇮", "flag: Slovenia", "flag slovenia"],
  ["🇸🇯", "flag: Svalbard & Jan Mayen", "flag svalbard jan mayen"],
  ["🇸🇰", "flag: Slovakia", "flag slovakia"],
  ["🇸🇱", "flag: Sierra Leone", "flag sierra leone"],
  ["🇸🇲", "flag: San Marino", "flag san marino"],
  ["🇸🇳", "flag: Senegal", "flag senegal"],
  ["🇸🇴", "flag: Somalia", "flag somalia"],
  ["🇸🇷", "flag: Suriname", "flag suriname"],
  ["🇸🇸", "flag: South Sudan", "flag south sudan"],
  ["🇸🇹", "flag: São Tomé & Príncipe", "flag so tom prncipe sao tome principe"],
  ["🇸🇻", "flag: El Salvador", "flag el salvador"],
  ["🇸🇽", "flag: Sint Maarten", "flag sint maarten"],
  ["🇸🇾", "flag: Syria", "flag syria"],
  ["🇸🇿", "flag: Eswatini", "flag eswatini swaziland"],
  ["🇹🇦", "flag: Tristan da Cunha", "flag tristan da cunha"],
  ["🇹🇨", "flag: Turks & Caicos Islands", "flag turks caicos islands"],
  ["🇹🇩", "flag: Chad", "flag chad"],
  ["🇹🇫", "flag: French Southern Territories", "flag french southern territories"],
  ["🇹🇬", "flag: Togo", "flag togo"],
  ["🇹🇭", "flag: Thailand", "flag thailand"],
  ["🇹🇯", "flag: Tajikistan", "flag tajikistan"],
  ["🇹🇰", "flag: Tokelau", "flag tokelau"],
  ["🇹🇱", "flag: Timor-Leste", "flag timor leste"],
  ["🇹🇲", "flag: Turkmenistan", "flag turkmenistan"],
  ["🇹🇳", "flag: Tunisia", "flag tunisia"],
  ["🇹🇴", "flag: Tonga", "flag tonga"],
  ["🇹🇷", "flag: Turkey", "flag turkey tr"],
  ["🇹🇹", "flag: Trinidad & Tobago", "flag trinidad tobago"],
  ["🇹🇻", "flag: Tuvalu", "flag tuvalu"],
  ["🇹🇼", "flag: Taiwan", "flag taiwan"],
  ["🇹🇿", "flag: Tanzania", "flag tanzania"],
  ["🇺🇦", "flag: Ukraine", "flag ukraine"],
  ["🇺🇬", "flag: Uganda", "flag uganda"],
  ["🇺🇲", "flag: U.S. Outlying Islands", "flag us outlying islands"],
  ["🇺🇳", "flag: United Nations", "flag united nations"],
  ["🇺🇸", "flag: United States", "flag united states america us"],
  ["🇺🇾", "flag: Uruguay", "flag uruguay"],
  ["🇺🇿", "flag: Uzbekistan", "flag uzbekistan"],
  ["🇻🇦", "flag: Vatican City", "flag vatican city"],
  ["🇻🇨", "flag: St. Vincent & Grenadines", "flag st vincent grenadines"],
  ["🇻🇪", "flag: Venezuela", "flag venezuela"],
  ["🇻🇬", "flag: British Virgin Islands", "flag british virgin islands"],
  ["🇻🇮", "flag: U.S. Virgin Islands", "flag us virgin islands"],
  ["🇻🇳", "flag: Vietnam", "flag vietnam"],
  ["🇻🇺", "flag: Vanuatu", "flag vanuatu"],
  ["🇼🇫", "flag: Wallis & Futuna", "flag wallis futuna"],
  ["🇼🇸", "flag: Samoa", "flag samoa"],
  ["🇽🇰", "flag: Kosovo", "flag kosovo"],
  ["🇾🇪", "flag: Yemen", "flag yemen"],
  ["🇾🇹", "flag: Mayotte", "flag mayotte"],
  ["🇿🇦", "flag: South Africa", "flag south africa"],
  ["🇿🇲", "flag: Zambia", "flag zambia"],
  ["🇿🇼", "flag: Zimbabwe", "flag zimbabwe"],
  ["🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f", "flag: England", "flag england"],
  ["🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f", "flag: Scotland", "flag scotland"],
  ["🏴\U000e0067\U000e0062\U000e0077\U000e006c\U000e0073\U000e007f", "flag: Wales", "flag wales"],
];
